---
knit: ({source(here::here("tools/knit.R")); knit_man_src})
---
Computes element-wise maximum on a list of inputs.

@description
It takes as input a list of tensors, all of the same shape,
and returns a single tensor (also of the same shape).

# Examples
```{r}
input_shape <- c(2, 3, 4)
x1 <- random_uniform(input_shape)
x2 <- random_uniform(input_shape)
y <- layer_maximum(x1, x2)
```

Usage in a Keras model:

```{r}
input1 <- layer_input(shape = c(16))
x1 <- input1 |> layer_dense(8, activation = 'relu')
input2 <- layer_input(shape = c(32))
x2 <- input2 |> layer_dense(8, activation = 'relu')
# equivalent to `y <- layer_maximum(x1, x2)`
y <- layer_maximum(x1, x2)
out <- y |> layer_dense(4)
model <- keras_model(inputs = c(input1, input2), outputs = out)
```

@param ...
Passed on to the Python callable

@param inputs
layers to combine

@export
@family maximum merging layers
@family merging layers
@family layers
@seealso
+ <https:/keras.io/api/layers/merging_layers/maximum#maximum-class>
+ <https://www.tensorflow.org/api_docs/python/tf/keras/layers/Maximum>
