---
knit: ({source(here::here("tools/knit.R")); knit_man_src})
---
Computes the crossentropy metric between the labels and predictions.

@description
Use this crossentropy metric when there are two or more label classes.
It expects labels to be provided as integers. If you want to provide labels
that are one-hot encoded, please use the `CategoricalCrossentropy`
metric instead.

There should be `num_classes` floating point values per feature for `y_pred`
and a single floating point value per feature for `y_true`.

# Examples
```python
y_true = [1, 2]
y_pred = [[0.05, 0.95, 0], [0.1, 0.8, 0.1]]
loss = keras.losses.sparse_categorical_crossentropy(y_true, y_pred)
assert loss.shape == (2,)
loss
# array([0.0513, 2.303], dtype=float32)
```
Standalone usage:

```python
# y_true = one_hot(y_true) = [[0, 1, 0], [0, 0, 1]]
# logits = log(y_pred)
# softmax = exp(logits) / sum(exp(logits), axis=-1)
# softmax = [[0.05, 0.95, EPSILON], [0.1, 0.8, 0.1]]
# xent = -sum(y * log(softmax), 1)
# log(softmax) = [[-2.9957, -0.0513, -16.1181],
#                [-2.3026, -0.2231, -2.3026]]
# y_true * log(softmax) = [[0, -0.0513, 0], [0, 0, -2.3026]]
# xent = [0.0513, 2.3026]
# Reduced xent = (0.0513 + 2.3026) / 2
m = keras.metrics.SparseCategoricalCrossentropy()
m.update_state([1, 2],
               [[0.05, 0.95, 0], [0.1, 0.8, 0.1]])
m.result()
# 1.1769392
```

```python
m.reset_state()
m.update_state([1, 2],
               [[0.05, 0.95, 0], [0.1, 0.8, 0.1]],
               sample_weight=np.array([0.3, 0.7]))
m.result()
# 1.6271976
```

Usage with `compile()` API:

```python
model.compile(
    optimizer='sgd',
    loss='mse',
    metrics=[keras.metrics.SparseCategoricalCrossentropy()])
```

@returns
Sparse categorical crossentropy loss value.

@param name
(Optional) string name of the metric instance.

@param dtype
(Optional) data type of the metric result.

@param from_logits
(Optional) Whether output is expected
to be a logits tensor. By default, we consider that output
encodes a probability distribution.

@param axis
(Optional) Defaults to `-1`.
The dimension along which entropy is computed.

@param y_true
Ground truth values.

@param y_pred
The predicted values.

@param ignore_class
Optional integer. The ID of a class to be ignored during
loss computation. This is useful, for example, in segmentation
problems featuring a "void" class (commonly -1 or 255) in
segmentation maps. By default (`ignore_class=None`), all classes are
considered.

@param ...
Passed on to the Python callable

@export
@family probabilistic metrics
@family metrics
@seealso
+ <https:/keras.io/api/metrics/probabilistic_metrics#sparsecategoricalcrossentropy-class>
+ <https://www.tensorflow.org/api_docs/python/tf/keras/metrics/SparseCategoricalCrossentropy>
