---
knit: ({source(here::here("tools/knit.R")); knit_man_src})
---
Draw samples from a uniform distribution.

@description
The generated values follow a uniform distribution in the range
`[minval, maxval)`. The lower bound `minval` is included in the range,
while the upper bound `maxval` is excluded.

`dtype` must be a floating point type, the default range is `[0, 1)`.

@param shape
The shape of the random values to generate.

@param minval
Float, defaults to 0. Lower bound of the range of
random values to generate (inclusive).

@param maxval
Float, defaults to 1. Upper bound of the range of
random values to generate (exclusive).

@param dtype
Optional dtype of the tensor. Only floating point types are
supported. If not specified, `keras.config.floatx()` is used,
which defaults to `float32` unless you configured it otherwise (via
`keras.config.set_floatx(float_dtype)`)

@param seed
A Python integer or instance of
`keras.random.SeedGenerator`.
Used to make the behavior of the initializer
deterministic. Note that an initializer seeded with an integer
or None (unseeded) will produce the same random values
across multiple calls. To get different random values
across multiple calls, use as seed an instance
of `keras.random.SeedGenerator`.

@export
@family random
@seealso
+ <https://www.tensorflow.org/api_docs/python/tf/keras/random/uniform>
