---
knit: ({source(here::here("tools/knit.R")); knit_man_src})
---
Calculates the mean and variance of `x`.

@description
The mean and variance are calculated by aggregating the contents of `x`
across `axes`. If `x` is 1-D and `axes = c(1)` this is just the mean and
variance of a vector.

# Examples
```{r}
x <- k_convert_to_tensor(c(0, 1, 2, 3, 100), dtype = "float32")
k_moments(x, axes = c(1))
```

@returns
A list containing two tensors - mean and variance.

@param x Input tensor.
@param axes A list of axes which to compute mean and variance.
@param keepdims If this is set to `TRUE`, the axes which are reduced are left
    in the result as dimensions with size one.
@param synchronized Only applicable with the TensorFlow backend.
    If `TRUE`, synchronizes the global batch statistics (mean and
    variance) across all devices at each training step in a
    distributed training strategy. If `FALSE`, each replica uses its own
    local batch statistics.

@export
@family ops
@seealso
+ <https://www.tensorflow.org/api_docs/python/tf/keras/ops/moments>

