---
knit: ({source(here::here("tools/knit.R")); knit_man_src})
---
Masks a sequence by using a mask value to skip timesteps.

@description
For each timestep in the input tensor (dimension #1 in the tensor),
if all values in the input tensor at that timestep
are equal to `mask_value`, then the timestep will be masked (skipped)
in all downstream layers (as long as they support masking).

If any downstream layer does not support masking yet receives such
an input mask, an exception will be raised.

# Examples
Consider an array `x` of shape `c(samples, timesteps, features)`,
to be fed to an LSTM layer. You want to mask timestep #3 and #5 because you
lack data for these timesteps. You can:

- Set `x[, 3, ] <- 0.` and `x[, 5, ] <- 0.`
- Insert a `layer_masking()` layer with `mask_value = 0.` before the LSTM layer:

```{r}
c(samples, timesteps, features) %<-% c(32, 10, 8)
inputs <- c(samples, timesteps, features) %>% { array(runif(prod(.)), dim = .) }
inputs[, 3, ] <- 0
inputs[, 5, ] <- 0

model <- keras_model_sequential() %>%
  layer_masking(mask_value = 0) %>%
  layer_lstm(32)

output <- model(inputs)
# The time step 3 and 5 will be skipped from LSTM calculation.
```

# Note
in the Keras masking convention, a masked timestep is denoted by
a mask value of `FALSE`, while a non-masked (i.e. usable) timestep
is denoted by a mask value of `TRUE`.

@param object Object to compose the layer with. A tensor, array, or sequential model.
@param ... Passed on to the Python callable
@param mask_value see description

@export
@family core layers
@seealso
+ <https:/keras.io/api/layers/core_layers/masking#masking-class>
+ <https://www.tensorflow.org/api_docs/python/tf/keras/layers/Masking>
