---
knit: ({source(here::here("tools/knit.R")); knit_man_src})
---
Computes categorical cross-entropy loss between target and output tensor.

@description
The categorical cross-entropy loss is commonly used in multi-class
classification tasks where each input sample can belong to one of
multiple classes. It measures the dissimilarity
between the target and output probabilities or logits.

# Examples
```{r}
target <- k_array(rbind(c(1, 0, 0),
                        c(0, 1, 0),
                        c(0, 0, 1)))
output <- k_array(rbind(c(0.9, 0.05, 0.05),
                        c(0.1, 0.8, 0.1),
                        c(0.2, 0.3, 0.5)))
k_categorical_crossentropy(target, output)
```

@returns
Integer tensor: The computed categorical cross-entropy loss between
`target` and `output`.

@param target
The target tensor representing the true categorical labels.
Its shape should match the shape of the `output` tensor
except for the last dimension.

@param output
The output tensor representing the predicted probabilities
or logits. Its shape should match the shape of the `target`
tensor except for the last dimension.

@param from_logits
(optional) Whether `output` is a tensor of logits or
probabilities.
Set it to `TRUE` if `output` represents logits; otherwise,
set it to `FALSE` if `output` represents probabilities.
Defaults to `FALSE`.

@param axis
(optional) The axis along which the categorical cross-entropy
is computed.
Defaults to `-1`, which corresponds to the last dimension of
the tensors.

@export
@family ops
@seealso
+ <https:/keras.io/keras_core/api/ops/nn#categoricalcrossentropy-function>
+ <https://www.tensorflow.org/api_docs/python/tf/keras/ops/categorical_crossentropy>
