---
knit: ({source(here::here("tools/knit.R")); knit_man_src})
---
Computes sparse categorical cross-entropy loss.

@description
The sparse categorical cross-entropy loss is similar to categorical
cross-entropy, but it is used when the target tensor contains integer
class labels instead of one-hot encoded vectors. It measures the
dissimilarity between the target and output probabilities or logits.

# Examples
```{r}
target <- k_array(c(0, 1, 2), dtype="int32")
output <- k_array(rbind(c(0.9, 0.05, 0.05), 
                        c(0.1, 0.8,  0.1), 
                        c(0.2, 0.3,  0.5)))
k_sparse_categorical_crossentropy(target, output)
```

@returns
Integer tensor: The computed sparse categorical cross-entropy
loss between `target` and `output`.

@param target
The target tensor representing the true class labels as
integers. Its shape should match the shape of the `output`
tensor except for the last dimension.

@param output
The output tensor representing the predicted probabilities
or logits.
Its shape should match the shape of the `target` tensor except
for the last dimension.

@param from_logits
(optional) Whether `output` is a tensor of logits
or probabilities.
Set it to `TRUE` if `output` represents logits; otherwise,
set it to `FALSE` if `output` represents probabilities.
Defaults to`FALSE`.

@param axis
(optional) The axis along which the sparse categorical
cross-entropy is computed.
Defaults to `-1`, which corresponds to the last dimension
of the tensors.

@export
@family ops
@seealso
+ <https:/keras.io/keras_core/api/ops/nn#sparsecategoricalcrossentropy-function>
+ <https://www.tensorflow.org/api_docs/python/tf/keras/ops/sparse_categorical_crossentropy>

