---
knit: ({source(here::here("tools/knit.R")); knit_man_src})
---
Computes binary cross-entropy loss between target and output tensor.

@description
The binary cross-entropy loss is commonly used in binary
classification tasks where each input sample belongs to one
of the two classes. It measures the dissimilarity between the
target and output probabilities or logits.

# Examples
```{r}
target <- k_array(c(0, 1, 1, 0))
output <- k_array(c(0.1, 0.9, 0.8, 0.2))
k_binary_crossentropy(target, output)
```

@returns
Integer tensor: The computed binary cross-entropy loss between
`target` and `output`.

@param target The target tensor representing the true binary labels.
    Its shape should match the shape of the `output` tensor.
@param output The output tensor representing the predicted probabilities
    or logits. Its shape should match the shape of the
    `target` tensor.
@param from_logits (optional) Whether `output` is a tensor of logits or
    probabilities.
    Set it to `TRUE` if `output` represents logits; otherwise,
    set it to `FALSE` if `output` represents probabilities.
    Defaults to `FALSE`.

@export
@family ops
@seealso
+ <https:/keras.io/keras_core/api/ops/nn#binarycrossentropy-function>
+ <https://www.tensorflow.org/api_docs/python/tf/keras/ops/binary_crossentropy>
