---
knit: ({source(here::here("tools/knit.R")); knit_man_src})
---
While loop implementation.

@description

# Examples

```{r}
i <- 0
loop_vars <- list(i)

# cond() must return a scalar bool
cond <- function(i) i < 10L

# body must return same shape as loop_vars
body <- function(i) list(i + 1L) 

k_while_loop(cond, body, loop_vars)
```

@returns
A list of tensors, has the same shape and dtype as `loop_vars`.

@param cond
A callable that represents the termination condition of the loop.
Must have the same number of args as `loop_vars`, and return a bool.

@param body
A callable that represents the loop body. Must have the same
number of args as `loop_vars`, and return a list of the same
length, shape and dtype as `loop_vars`.

@param loop_vars
A list of tensors, the loop variables.

@param maximum_iterations
Optional maximum number of iterations of the while
loop to run. If provided, the `cond` output is AND-ed with an
additional condition ensuring the number of iterations executed is
no greater than `maximum_iterations`.

@export
@family core ops
@family ops
@seealso
+ <https:/keras.io/keras_core/api/ops/core#whileloop-function>
+ <https://www.tensorflow.org/api_docs/python/tf/keras/ops/while_loop>

