---
knit: ({source(here::here("tools/knit.R")); knit_man_src})
---
Performs elementwise subtraction.

@description
It takes as input a list of tensors of size 2 both of the
same shape, and returns a single tensor `(inputs[0] - inputs[1))`
of same shape.

# Examples
```{r}
input_shape <- c(2, 3, 4)
x1 <- random_uniform(input_shape)
x2 <- random_uniform(input_shape)
y <- layer_subtract(list(x1, x2))
```

Usage in a Keras model:

```{r}
input1 <- layer_input(shape = 16)
x1 <- layer_dense(input1, units = 8, activation = 'relu')
input2 <- layer_input(shape = 32)
x2 <- layer_dense(input2, units = 8, activation = 'relu')
subtracted <- layer_subtract(list(x1, x2))
out <- layer_dense(subtracted, units = 4)
model <- keras_model(inputs = list(input1, input2), outputs = out)
```

@param ...
Passed on to the Python callable

@param inputs
layers to combine

@export
@family merging layers
@seealso
+ <https:/keras.io/api/layers/merging_layers/subtract#subtract-class>
+ <https://www.tensorflow.org/api_docs/python/tf/keras/layers/Subtract>

