---
knit: ({source(here::here("tools/knit.R")); knit_man_src})
---
Grouped Query Attention layer.

@description
This is an implementation of grouped-query attention introduced by
[Ainslie et al., 2023](https://arxiv.org/abs/2305.13245). Here
`num_key_value_heads` denotes number of groups, setting
`num_key_value_heads` to 1 is equivalent to multi-query attention, and
when `num_key_value_heads` is equal to `num_query_heads` it is equivalent
to multi-head attention.

This layer first projects `query`, `key`, and `value` tensors. Then, `key`
and `value` are repeated to match the number of heads of `query`.

Then, the `query` is scaled and dot-producted with `key` tensors. These are
softmaxed to obtain attention probabilities. The value tensors are then
interpolated by these probabilities and concatenated back to a single
tensor.

# Call Arguments
- `query`: Query tensor of shape `(batch_dim, target_seq_len, feature_dim)`,
    where `batch_dim` is batch size, `target_seq_len` is the length of
    target sequence, and `feature_dim` is dimension of feature.
- `value`: Value tensor of shape `(batch_dim, source_seq_len, feature_dim)`,
    where `batch_dim` is batch size, `source_seq_len` is the length of
    source sequence, and `feature_dim` is dimension of feature.
- `key`: Optional key tensor of shape
    `(batch_dim, source_seq_len, feature_dim)`. If not given, will use
    `value` for both `key` and `value`, which is most common case.
- `attention_mask`: A boolean mask of shape
    `(batch_dim, target_seq_len, source_seq_len)`, that prevents
    attention to certain positions. The boolean mask specifies which
    query elements can attend to which key elements, where 1 indicates
    attention and 0 indicates no attention. Broadcasting can happen for
    the missing batch dimensions and the head dimension.
- `return_attention_scores`: A boolean to indicate whether the output
    should be `(attention_output, attention_scores)` if `True`, or
    `attention_output` if `False`. Defaults to `False`.
- `training`: Python boolean indicating whether the layer should behave in
    training mode (adding dropout) or in inference mode (no dropout).
    Will go with either using the training mode of the parent
    layer/model or `False` (inference) if there is no parent layer.
- `use_causal_mask`: A boolean to indicate whether to apply a causal mask to
    prevent tokens from attending to future tokens (e.g., used in a
    decoder Transformer).

@returns
attention_output: Result of the computation, of shape
    `(batch_dim, target_seq_len, feature_dim)`, where `target_seq_len`
    is for target sequence length and `feature_dim` is the query input
    last dim.
attention_scores: (Optional) attention coefficients of shape
    `(batch_dim, num_query_heads, target_seq_len, source_seq_len)`.

@param head_dim
Size of each attention head.

@param num_query_heads
Number of query attention heads.

@param num_key_value_heads
Number of key and value attention heads.

@param dropout
Dropout probability.

@param use_bias
Boolean, whether the dense layers use bias vectors/matrices.

@param kernel_initializer
Initializer for dense layer kernels.

@param bias_initializer
Initializer for dense layer biases.

@param kernel_regularizer
Regularizer for dense layer kernels.

@param bias_regularizer
Regularizer for dense layer biases.

@param activity_regularizer
Regularizer for dense layer activity.

@param kernel_constraint
Constraint for dense layer kernels.

@param bias_constraint
Constraint for dense layer kernels.

@param object
Object to compose the layer with. A tensor, array, or sequential model.

@param ...
Passed on to the Python callable

@export
@family attention layers
@seealso
+ <https://www.tensorflow.org/api_docs/python/tf/keras/layers/GroupQueryAttention>
