## Autogenerated. Do not modify manually.


"man-src/config_backend.Rmd" # |>file.edit() # or cmd+click to edit man page
"man-src/config_backend/0-upstream.md" # view the upstream doc
#' @eval readLines("man-src/config_backend/3-rendered.md")
config_backend <-
function ()
{
    args <- capture_args2(NULL)
    do.call(keras$config$backend, args)
}


"man-src/config_epsilon.Rmd" # |>file.edit() # or cmd+click to edit man page
"man-src/config_epsilon/0-upstream.md" # view the upstream doc
#' @eval readLines("man-src/config_epsilon/3-rendered.md")
config_epsilon <-
function ()
{
    args <- capture_args2(NULL)
    do.call(keras$config$epsilon, args)
}


"man-src/config_floatx.Rmd" # |>file.edit() # or cmd+click to edit man page
"man-src/config_floatx/0-upstream.md" # view the upstream doc
#' @eval readLines("man-src/config_floatx/3-rendered.md")
config_floatx <-
function ()
{
    args <- capture_args2(NULL)
    do.call(keras$config$floatx, args)
}


"man-src/config_image_data_format.Rmd" # |>file.edit() # or cmd+click to edit man page
"man-src/config_image_data_format/0-upstream.md" # view the upstream doc
#' @eval readLines("man-src/config_image_data_format/3-rendered.md")
config_image_data_format <-
function ()
{
    args <- capture_args2(NULL)
    do.call(keras$config$image_data_format, args)
}


"man-src/config_set_epsilon.Rmd" # |>file.edit() # or cmd+click to edit man page
"man-src/config_set_epsilon/0-upstream.md" # view the upstream doc
#' @eval readLines("man-src/config_set_epsilon/3-rendered.md")
config_set_epsilon <-
function (value)
{
    args <- capture_args2(NULL)
    do.call(keras$config$set_epsilon, args)
}


"man-src/config_set_floatx.Rmd" # |>file.edit() # or cmd+click to edit man page
"man-src/config_set_floatx/0-upstream.md" # view the upstream doc
#' @eval readLines("man-src/config_set_floatx/3-rendered.md")
config_set_floatx <-
function (value)
{
    args <- capture_args2(NULL)
    do.call(keras$config$set_floatx, args)
}


"man-src/config_set_image_data_format.Rmd" # |>file.edit() # or cmd+click to edit man page
"man-src/config_set_image_data_format/0-upstream.md" # view the upstream doc
#' @eval readLines("man-src/config_set_image_data_format/3-rendered.md")
config_set_image_data_format <-
function (data_format)
{
    args <- capture_args2(NULL)
    do.call(keras$config$set_image_data_format, args)
}


"man-src/config_enable_unsafe_deserialization.Rmd" # |>file.edit() # or cmd+click to edit man page
"man-src/config_enable_unsafe_deserialization/0-upstream.md" # view the upstream doc
#' @eval readLines("man-src/config_enable_unsafe_deserialization/3-rendered.md")
config_enable_unsafe_deserialization <-
function ()
{
    args <- capture_args2(NULL)
    do.call(keras$config$enable_unsafe_deserialization, args)
}


"man-src/config_disable_interactive_logging.Rmd" # |>file.edit() # or cmd+click to edit man page
"man-src/config_disable_interactive_logging/0-upstream.md" # view the upstream doc
#' @eval readLines("man-src/config_disable_interactive_logging/3-rendered.md")
config_disable_interactive_logging <-
function ()
{
    args <- capture_args2(NULL)
    do.call(keras$config$disable_interactive_logging, args)
}


"man-src/config_enable_interactive_logging.Rmd" # |>file.edit() # or cmd+click to edit man page
"man-src/config_enable_interactive_logging/0-upstream.md" # view the upstream doc
#' @eval readLines("man-src/config_enable_interactive_logging/3-rendered.md")
config_enable_interactive_logging <-
function ()
{
    args <- capture_args2(NULL)
    do.call(keras$config$enable_interactive_logging, args)
}


"man-src/config_is_interactive_logging_enabled.Rmd" # |>file.edit() # or cmd+click to edit man page
"man-src/config_is_interactive_logging_enabled/0-upstream.md" # view the upstream doc
#' @eval readLines("man-src/config_is_interactive_logging_enabled/3-rendered.md")
config_is_interactive_logging_enabled <-
function ()
{
    args <- capture_args2(NULL)
    do.call(keras$config$is_interactive_logging_enabled, args)
}


"man-src/config_disable_traceback_filtering.Rmd" # |>file.edit() # or cmd+click to edit man page
"man-src/config_disable_traceback_filtering/0-upstream.md" # view the upstream doc
#' @eval readLines("man-src/config_disable_traceback_filtering/3-rendered.md")
config_disable_traceback_filtering <-
function ()
{
    args <- capture_args2(NULL)
    do.call(keras$config$disable_traceback_filtering, args)
}


"man-src/config_enable_traceback_filtering.Rmd" # |>file.edit() # or cmd+click to edit man page
"man-src/config_enable_traceback_filtering/0-upstream.md" # view the upstream doc
#' @eval readLines("man-src/config_enable_traceback_filtering/3-rendered.md")
config_enable_traceback_filtering <-
function ()
{
    args <- capture_args2(NULL)
    do.call(keras$config$enable_traceback_filtering, args)
}


"man-src/config_is_traceback_filtering_enabled.Rmd" # |>file.edit() # or cmd+click to edit man page
"man-src/config_is_traceback_filtering_enabled/0-upstream.md" # view the upstream doc
#' @eval readLines("man-src/config_is_traceback_filtering_enabled/3-rendered.md")
config_is_traceback_filtering_enabled <-
function ()
{
    args <- capture_args2(NULL)
    do.call(keras$config$is_traceback_filtering_enabled, args)
}
