## Autogenerated. Do not modify manually.


#' @eval readLines("man-roxygen/config_backend/roxygen.Rmd")
config_backend <-
function ()
{
    args <- capture_args2(NULL)
    do.call(keras$config$backend, args)
}


#' @eval readLines("man-roxygen/config_epsilon/roxygen.Rmd")
config_epsilon <-
function ()
{
    args <- capture_args2(NULL)
    do.call(keras$config$epsilon, args)
}


#' @eval readLines("man-roxygen/config_floatx/roxygen.Rmd")
config_floatx <-
function ()
{
    args <- capture_args2(NULL)
    do.call(keras$config$floatx, args)
}


#' @eval readLines("man-roxygen/config_image_data_format/roxygen.Rmd")
config_image_data_format <-
function ()
{
    args <- capture_args2(NULL)
    do.call(keras$config$image_data_format, args)
}


#' @eval readLines("man-roxygen/config_set_epsilon/roxygen.Rmd")
config_set_epsilon <-
function (value)
{
    args <- capture_args2(NULL)
    do.call(keras$config$set_epsilon, args)
}


#' @eval readLines("man-roxygen/config_set_floatx/roxygen.Rmd")
config_set_floatx <-
function (value)
{
    args <- capture_args2(NULL)
    do.call(keras$config$set_floatx, args)
}


#' @eval readLines("man-roxygen/config_set_image_data_format/roxygen.Rmd")
config_set_image_data_format <-
function (data_format)
{
    args <- capture_args2(NULL)
    do.call(keras$config$set_image_data_format, args)
}


#' @eval readLines("man-roxygen/config_enable_unsafe_deserialization/roxygen.Rmd")
config_enable_unsafe_deserialization <-
function ()
{
    args <- capture_args2(NULL)
    do.call(keras$config$enable_unsafe_deserialization, args)
}


#' @eval readLines("man-roxygen/config_disable_interactive_logging/roxygen.Rmd")
config_disable_interactive_logging <-
function ()
{
    args <- capture_args2(NULL)
    do.call(keras$config$disable_interactive_logging, args)
}


#' @eval readLines("man-roxygen/config_enable_interactive_logging/roxygen.Rmd")
config_enable_interactive_logging <-
function ()
{
    args <- capture_args2(NULL)
    do.call(keras$config$enable_interactive_logging, args)
}


#' @eval readLines("man-roxygen/config_is_interactive_logging_enabled/roxygen.Rmd")
config_is_interactive_logging_enabled <-
function ()
{
    args <- capture_args2(NULL)
    do.call(keras$config$is_interactive_logging_enabled, args)
}


#' @eval readLines("man-roxygen/config_disable_traceback_filtering/roxygen.Rmd")
config_disable_traceback_filtering <-
function ()
{
    args <- capture_args2(NULL)
    do.call(keras$config$disable_traceback_filtering, args)
}


#' @eval readLines("man-roxygen/config_enable_traceback_filtering/roxygen.Rmd")
config_enable_traceback_filtering <-
function ()
{
    args <- capture_args2(NULL)
    do.call(keras$config$enable_traceback_filtering, args)
}


#' @eval readLines("man-roxygen/config_is_traceback_filtering_enabled/roxygen.Rmd")
config_is_traceback_filtering_enabled <-
function ()
{
    args <- capture_args2(NULL)
    do.call(keras$config$is_traceback_filtering_enabled, args)
}
