## Autogenerated. Do not modify manually.


#' @eval readLines("man-roxygen/activation_elu/roxygen.Rmd")
activation_elu <-
structure(function (x, alpha = 1)
{
    args <- capture_args2(NULL)
    do.call(keras$activations$elu, args)
}, py_function_name = "elu")


#' @eval readLines("man-roxygen/activation_exponential/roxygen.Rmd")
activation_exponential <-
structure(function (x)
{
    args <- capture_args2(NULL)
    do.call(keras$activations$exponential, args)
}, py_function_name = "exponential")


#' @eval readLines("man-roxygen/activation_gelu/roxygen.Rmd")
activation_gelu <-
structure(function (x, approximate = FALSE)
{
    args <- capture_args2(NULL)
    do.call(keras$activations$gelu, args)
}, py_function_name = "gelu")


#' @eval readLines("man-roxygen/activation_hard_sigmoid/roxygen.Rmd")
activation_hard_sigmoid <-
structure(function (x)
{
    args <- capture_args2(NULL)
    do.call(keras$activations$hard_sigmoid, args)
}, py_function_name = "hard_sigmoid")


#' @eval readLines("man-roxygen/activation_leaky_relu/roxygen.Rmd")
activation_leaky_relu <-
structure(function (x, negative_slope = 0.2)
{
    args <- capture_args2(NULL)
    do.call(keras$activations$leaky_relu, args)
}, py_function_name = "leaky_relu")


#' @eval readLines("man-roxygen/activation_linear/roxygen.Rmd")
activation_linear <-
structure(function (x)
{
    args <- capture_args2(NULL)
    do.call(keras$activations$linear, args)
}, py_function_name = "linear")


#' @eval readLines("man-roxygen/activation_log_softmax/roxygen.Rmd")
activation_log_softmax <-
structure(function (x, axis = -1L)
{
    args <- capture_args2(list(axis = as_axis))
    do.call(keras$activations$log_softmax, args)
}, py_function_name = "log_softmax")


#' @eval readLines("man-roxygen/activation_mish/roxygen.Rmd")
activation_mish <-
structure(function (x)
{
    args <- capture_args2(NULL)
    do.call(keras$activations$mish, args)
}, py_function_name = "mish")


#' @eval readLines("man-roxygen/activation_relu/roxygen.Rmd")
activation_relu <-
structure(function (x, negative_slope = 0, max_value = NULL,
    threshold = 0)
{
    args <- capture_args2(NULL)
    do.call(keras$activations$relu, args)
}, py_function_name = "relu")


#' @eval readLines("man-roxygen/activation_relu6/roxygen.Rmd")
activation_relu6 <-
structure(function (x)
{
    args <- capture_args2(NULL)
    do.call(keras$activations$relu6, args)
}, py_function_name = "relu6")


#' @eval readLines("man-roxygen/activation_selu/roxygen.Rmd")
activation_selu <-
structure(function (x)
{
    args <- capture_args2(NULL)
    do.call(keras$activations$selu, args)
}, py_function_name = "selu")


#' @eval readLines("man-roxygen/activation_sigmoid/roxygen.Rmd")
activation_sigmoid <-
structure(function (x)
{
    args <- capture_args2(NULL)
    do.call(keras$activations$sigmoid, args)
}, py_function_name = "sigmoid")


#' @eval readLines("man-roxygen/activation_silu/roxygen.Rmd")
activation_silu <-
structure(function (x)
{
    args <- capture_args2(NULL)
    do.call(keras$activations$silu, args)
}, py_function_name = "silu")


#' @eval readLines("man-roxygen/activation_softmax/roxygen.Rmd")
activation_softmax <-
structure(function (x, axis = -1L)
{
    args <- capture_args2(list(axis = as_axis))
    do.call(keras$activations$softmax, args)
}, py_function_name = "softmax")


#' @eval readLines("man-roxygen/activation_softplus/roxygen.Rmd")
activation_softplus <-
structure(function (x)
{
    args <- capture_args2(NULL)
    do.call(keras$activations$softplus, args)
}, py_function_name = "softplus")


#' @eval readLines("man-roxygen/activation_softsign/roxygen.Rmd")
activation_softsign <-
structure(function (x)
{
    args <- capture_args2(NULL)
    do.call(keras$activations$softsign, args)
}, py_function_name = "softsign")


#' @eval readLines("man-roxygen/activation_tanh/roxygen.Rmd")
activation_tanh <-
structure(function (x)
{
    args <- capture_args2(NULL)
    do.call(keras$activations$tanh, args)
}, py_function_name = "tanh")
