## Autogenerated. Do not modify manually.


#        file.edit("man-src/initializer_constant/2-translated.Rmd")
#' @eval readLines("man-src/initializer_constant/3-rendered.md")
initializer_constant <-
function (value = 0)
{
    args <- capture_args2(NULL)
    do.call(keras$initializers$Constant, args)
}


#        file.edit("man-src/initializer_identity/2-translated.Rmd")
#' @eval readLines("man-src/initializer_identity/3-rendered.md")
initializer_identity <-
function (gain = 1)
{
    args <- capture_args2(NULL)
    do.call(keras$initializers$IdentityInitializer, args)
}


#        file.edit("man-src/initializer_ones/2-translated.Rmd")
#' @eval readLines("man-src/initializer_ones/3-rendered.md")
initializer_ones <-
function ()
{
    args <- capture_args2(NULL)
    do.call(keras$initializers$Ones, args)
}


#        file.edit("man-src/initializer_zeros/2-translated.Rmd")
#' @eval readLines("man-src/initializer_zeros/3-rendered.md")
initializer_zeros <-
function ()
{
    args <- capture_args2(NULL)
    do.call(keras$initializers$Zeros, args)
}


#        file.edit("man-src/initializer_glorot_normal/2-translated.Rmd")
#' @eval readLines("man-src/initializer_glorot_normal/3-rendered.md")
initializer_glorot_normal <-
function (seed = NULL)
{
    args <- capture_args2(list(seed = as_integer))
    do.call(keras$initializers$GlorotNormal, args)
}


#        file.edit("man-src/initializer_glorot_uniform/2-translated.Rmd")
#' @eval readLines("man-src/initializer_glorot_uniform/3-rendered.md")
initializer_glorot_uniform <-
function (seed = NULL)
{
    args <- capture_args2(list(seed = as_integer))
    do.call(keras$initializers$GlorotUniform, args)
}


#        file.edit("man-src/initializer_he_normal/2-translated.Rmd")
#' @eval readLines("man-src/initializer_he_normal/3-rendered.md")
initializer_he_normal <-
function (seed = NULL)
{
    args <- capture_args2(list(seed = as_integer))
    do.call(keras$initializers$HeNormal, args)
}


#        file.edit("man-src/initializer_he_uniform/2-translated.Rmd")
#' @eval readLines("man-src/initializer_he_uniform/3-rendered.md")
initializer_he_uniform <-
function (seed = NULL)
{
    args <- capture_args2(list(seed = as_integer))
    do.call(keras$initializers$HeUniform, args)
}


#        file.edit("man-src/initializer_lecun_normal/2-translated.Rmd")
#' @eval readLines("man-src/initializer_lecun_normal/3-rendered.md")
initializer_lecun_normal <-
function (seed = NULL)
{
    args <- capture_args2(list(seed = as_integer))
    do.call(keras$initializers$LecunNormal, args)
}


#        file.edit("man-src/initializer_lecun_uniform/2-translated.Rmd")
#' @eval readLines("man-src/initializer_lecun_uniform/3-rendered.md")
initializer_lecun_uniform <-
function (seed = NULL)
{
    args <- capture_args2(list(seed = as_integer))
    do.call(keras$initializers$LecunUniform, args)
}


#        file.edit("man-src/initializer_orthogonal/2-translated.Rmd")
#' @eval readLines("man-src/initializer_orthogonal/3-rendered.md")
initializer_orthogonal <-
function (gain = 1, seed = NULL)
{
    args <- capture_args2(list(seed = as_integer))
    do.call(keras$initializers$OrthogonalInitializer, args)
}


#        file.edit("man-src/initializer_random_normal/2-translated.Rmd")
#' @eval readLines("man-src/initializer_random_normal/3-rendered.md")
initializer_random_normal <-
function (mean = 0, stddev = 0.05, seed = NULL)
{
    args <- capture_args2(list(seed = as_integer))
    do.call(keras$initializers$RandomNormal, args)
}


#        file.edit("man-src/initializer_random_uniform/2-translated.Rmd")
#' @eval readLines("man-src/initializer_random_uniform/3-rendered.md")
initializer_random_uniform <-
function (minval = -0.05, maxval = 0.05, seed = NULL)
{
    args <- capture_args2(list(seed = as_integer))
    do.call(keras$initializers$RandomUniform, args)
}


#        file.edit("man-src/initializer_truncated_normal/2-translated.Rmd")
#' @eval readLines("man-src/initializer_truncated_normal/3-rendered.md")
initializer_truncated_normal <-
function (mean = 0, stddev = 0.05, seed = NULL)
{
    args <- capture_args2(list(seed = as_integer))
    do.call(keras$initializers$TruncatedNormal, args)
}


#        file.edit("man-src/initializer_variance_scaling/2-translated.Rmd")
#' @eval readLines("man-src/initializer_variance_scaling/3-rendered.md")
initializer_variance_scaling <-
function (scale = 1, mode = "fan_in", distribution = "truncated_normal",
    seed = NULL)
{
    args <- capture_args2(list(seed = as_integer))
    do.call(keras$initializers$VarianceScaling, args)
}
