## Autogenerated. Do not modify manually.


# keras$layers$image_dataset_from_directory
# keras_core.src.utils.image_dataset_utils.image_dataset_from_directory
r"-(Generates a `tf.data.Dataset` from image files in a directory.

    If your directory structure is:

    ```
    main_directory/
    ...class_a/
    ......a_image_1.jpg
    ......a_image_2.jpg
    ...class_b/
    ......b_image_1.jpg
    ......b_image_2.jpg
    ```

    Then calling `image_dataset_from_directory(main_directory,
    labels='inferred')` will return a `tf.data.Dataset` that yields batches of
    images from the subdirectories `class_a` and `class_b`, together with labels
    0 and 1 (0 corresponding to `class_a` and 1 corresponding to `class_b`).

    Supported image formats: `.jpeg`, `.jpg`, `.png`, `.bmp`, `.gif`.
    Animated gifs are truncated to the first frame.

    Args:
        directory: Directory where the data is located.
            If `labels` is `"inferred"`, it should contain
            subdirectories, each containing images for a class.
            Otherwise, the directory structure is ignored.
        labels: Either `"inferred"`
            (labels are generated from the directory structure),
            `None` (no labels),
            or a list/tuple of integer labels of the same size as the number of
            image files found in the directory. Labels should be sorted
            according to the alphanumeric order of the image file paths
            (obtained via `os.walk(directory)` in Python).
        label_mode: String describing the encoding of `labels`. Options are:
            - `"int"`: means that the labels are encoded as integers
                (e.g. for `sparse_categorical_crossentropy` loss).
            - `"categorical"` means that the labels are
                encoded as a categorical vector
                (e.g. for `categorical_crossentropy` loss).
            - `"binary"` means that the labels (there can be only 2)
                are encoded as `float32` scalars with values 0 or 1
                (e.g. for `binary_crossentropy`).
            - `None` (no labels).
        class_names: Only valid if `labels` is `"inferred"`.
            This is the explicit list of class names
            (must match names of subdirectories). Used to control the order
            of the classes (otherwise alphanumerical order is used).
        color_mode: One of `"grayscale"`, `"rgb"`, `"rgba"`.
            Defaults to `"rgb"`. Whether the images will be converted to
            have 1, 3, or 4 channels.
        batch_size: Size of the batches of data. Defaults to 32.
            If `None`, the data will not be batched
            (the dataset will yield individual samples).
        image_size: Size to resize images to after they are read from disk,
            specified as `(height, width)`. Defaults to `(256, 256)`.
            Since the pipeline processes batches of images that must all have
            the same size, this must be provided.
        shuffle: Whether to shuffle the data. Defaults to `True`.
            If set to `False`, sorts the data in alphanumeric order.
        seed: Optional random seed for shuffling and transformations.
        validation_split: Optional float between 0 and 1,
            fraction of data to reserve for validation.
        subset: Subset of the data to return.
            One of `"training"`, `"validation"`, or `"both"`.
            Only used if `validation_split` is set.
            When `subset="both"`, the utility returns a tuple of two datasets
            (the training and validation datasets respectively).
        interpolation: String, the interpolation method used when
            resizing images. Defaults to `"bilinear"`.
            Supports `"bilinear"`, `"nearest"`, `"bicubic"`, `"area"`,
            `"lanczos3"`, `"lanczos5"`, `"gaussian"`, `"mitchellcubic"`.
        follow_links: Whether to visit subdirectories pointed to by symlinks.
            Defaults to `False`.
        crop_to_aspect_ratio: If `True`, resize the images without aspect
            ratio distortion. When the original aspect ratio differs from the
            target aspect ratio, the output image will be cropped so as to
            return the largest possible window in the image
            (of size `image_size`) that matches the target aspect ratio. By
            default (`crop_to_aspect_ratio=False`), aspect ratio may not be
            preserved.
        data_format: If None uses keras.config.image_data_format()
            otherwise either 'channel_last' or 'channel_first'.

    Returns:

    A `tf.data.Dataset` object.

    - If `label_mode` is `None`, it yields `float32` tensors of shape
        `(batch_size, image_size[0], image_size[1], num_channels)`,
        encoding images (see below for rules regarding `num_channels`).
    - Otherwise, it yields a tuple `(images, labels)`, where `images` has
        shape `(batch_size, image_size[0], image_size[1], num_channels)`,
        and `labels` follows the format described below.

    Rules regarding labels format:

    - if `label_mode` is `"int"`, the labels are an `int32` tensor of shape
        `(batch_size,)`.
    - if `label_mode` is `"binary"`, the labels are a `float32` tensor of
        1s and 0s of shape `(batch_size, 1)`.
    - if `label_mode` is `"categorical"`, the labels are a `float32` tensor
        of shape `(batch_size, num_classes)`, representing a one-hot
        encoding of the class index.

    Rules regarding number of channels in the yielded images:

    - if `color_mode` is `"grayscale"`,
        there's 1 channel in the image tensors.
    - if `color_mode` is `"rgb"`,
        there are 3 channels in the image tensors.
    - if `color_mode` is `"rgba"`,
        there are 4 channels in the image tensors.
    )-"


# keras_core.src.utils.image_dataset_utils.image_dataset_from_directory
#' Generates a `tf.data.Dataset` from image files in a directory.
#'
#' @description
#' If your directory structure is:
#'
#' ```
#' main_directory/
#' ...class_a/
#' ......a_image_1.jpg
#' ......a_image_2.jpg
#' ...class_b/
#' ......b_image_1.jpg
#' ......b_image_2.jpg
#' ```
#'
#' Then calling `image_dataset_from_directory(main_directory,
#' labels='inferred')` will return a `tf.data.Dataset` that yields batches of
#' images from the subdirectories `class_a` and `class_b`, together with labels
#' 0 and 1 (0 corresponding to `class_a` and 1 corresponding to `class_b`).
#'
#' Supported image formats: `.jpeg`, `.jpg`, `.png`, `.bmp`, `.gif`.
#' Animated gifs are truncated to the first frame.
#'
#' # Returns
#' A `tf.data.Dataset` object.
#'
#' - If `label_mode` is `None`, it yields `float32` tensors of shape
#'     `(batch_size, image_size[0], image_size[1], num_channels)`,
#'     encoding images (see below for rules regarding `num_channels`).
#' - Otherwise, it yields a tuple `(images, labels)`, where `images` has
#'     shape `(batch_size, image_size[0], image_size[1], num_channels)`,
#'     and `labels` follows the format described below.
#'
#' Rules regarding labels format:
#'
#' - if `label_mode` is `"int"`, the labels are an `int32` tensor of shape
#'     `(batch_size,)`.
#' - if `label_mode` is `"binary"`, the labels are a `float32` tensor of
#'     1s and 0s of shape `(batch_size, 1)`.
#' - if `label_mode` is `"categorical"`, the labels are a `float32` tensor
#'     of shape `(batch_size, num_classes)`, representing a one-hot
#'     encoding of the class index.
#'
#' Rules regarding number of channels in the yielded images:
#'
#' - if `color_mode` is `"grayscale"`,
#'     there's 1 channel in the image tensors.
#' - if `color_mode` is `"rgb"`,
#'     there are 3 channels in the image tensors.
#' - if `color_mode` is `"rgba"`,
#'     there are 4 channels in the image tensors.
#'
#' @param directory Directory where the data is located.
#'     If `labels` is `"inferred"`, it should contain
#'     subdirectories, each containing images for a class.
#'     Otherwise, the directory structure is ignored.
#' @param labels Either `"inferred"`
#'     (labels are generated from the directory structure),
#'     `None` (no labels),
#'     or a list/tuple of integer labels of the same size as the number of
#'     image files found in the directory. Labels should be sorted
#'     according to the alphanumeric order of the image file paths
#'     (obtained via `os.walk(directory)` in Python).
#' @param label_mode String describing the encoding of `labels`. Options are:
#'     - `"int"`: means that the labels are encoded as integers
#'         (e.g. for `sparse_categorical_crossentropy` loss).
#'     - `"categorical"` means that the labels are
#'         encoded as a categorical vector
#'         (e.g. for `categorical_crossentropy` loss).
#'     - `"binary"` means that the labels (there can be only 2)
#'         are encoded as `float32` scalars with values 0 or 1
#'         (e.g. for `binary_crossentropy`).
#'     - `None` (no labels).
#' @param class_names Only valid if `labels` is `"inferred"`.
#'     This is the explicit list of class names
#'     (must match names of subdirectories). Used to control the order
#'     of the classes (otherwise alphanumerical order is used).
#' @param color_mode One of `"grayscale"`, `"rgb"`, `"rgba"`.
#'     Defaults to `"rgb"`. Whether the images will be converted to
#'     have 1, 3, or 4 channels.
#' @param batch_size Size of the batches of data. Defaults to 32.
#'     If `None`, the data will not be batched
#'     (the dataset will yield individual samples).
#' @param image_size Size to resize images to after they are read from disk,
#'     specified as `(height, width)`. Defaults to `(256, 256)`.
#'     Since the pipeline processes batches of images that must all have
#'     the same size, this must be provided.
#' @param shuffle Whether to shuffle the data. Defaults to `True`.
#'     If set to `False`, sorts the data in alphanumeric order.
#' @param seed Optional random seed for shuffling and transformations.
#' @param validation_split Optional float between 0 and 1,
#'     fraction of data to reserve for validation.
#' @param subset Subset of the data to return.
#'     One of `"training"`, `"validation"`, or `"both"`.
#'     Only used if `validation_split` is set.
#'     When `subset="both"`, the utility returns a tuple of two datasets
#'     (the training and validation datasets respectively).
#' @param interpolation String, the interpolation method used when
#'     resizing images. Defaults to `"bilinear"`.
#'     Supports `"bilinear"`, `"nearest"`, `"bicubic"`, `"area"`,
#'     `"lanczos3"`, `"lanczos5"`, `"gaussian"`, `"mitchellcubic"`.
#' @param follow_links Whether to visit subdirectories pointed to by symlinks.
#'     Defaults to `False`.
#' @param crop_to_aspect_ratio If `True`, resize the images without aspect
#'     ratio distortion. When the original aspect ratio differs from the
#'     target aspect ratio, the output image will be cropped so as to
#'     return the largest possible window in the image
#'     (of size `image_size`) that matches the target aspect ratio. By
#'     default (`crop_to_aspect_ratio=False`), aspect ratio may not be
#'     preserved.
#' @param data_format If None uses keras.config.image_data_format()
#'     otherwise either 'channel_last' or 'channel_first'.
#'
#' @export
#' @seealso
#' + <https://www.tensorflow.org/api_docs/python/tf/keras/preprocessing/image_dataset_from_directory>
image_dataset_from_directory <-
function (directory, labels = "inferred", label_mode = "int",
    class_names = NULL, color_mode = "rgb", batch_size = 32L,
    image_size = list(256L, 256L), shuffle = TRUE, seed = NULL,
    validation_split = NULL, subset = NULL, interpolation = "bilinear",
    follow_links = FALSE, crop_to_aspect_ratio = FALSE, data_format = NULL)
{
    args <- capture_args2(list(labels = as_integer, label_mode = as_integer,
        batch_size = as_integer))
    do.call(keras$preprocessing$image_dataset_from_directory,
        args)
}


# keras$layers$save_img
# keras_core.src.utils.image_utils.save_img
r"-(Saves an image stored as a NumPy array to a path or file object.

    Args:
        path: Path or file object.
        x: NumPy array.
        data_format: Image data format, either `"channels_first"` or
            `"channels_last"`.
        file_format: Optional file format override. If omitted, the format to
            use is determined from the filename extension. If a file object was
            used instead of a filename, this parameter should always be used.
        scale: Whether to rescale image values to be within `[0, 255]`.
        **kwargs: Additional keyword arguments passed to `PIL.Image.save()`.
    )-"


# keras_core.src.utils.image_utils.save_img
#' Saves an image stored as a NumPy array to a path or file object.
#'
#' @param path Path or file object.
#' @param x NumPy array.
#' @param data_format Image data format, either `"channels_first"` or
#'     `"channels_last"`.
#' @param file_format Optional file format override. If omitted, the format to
#'     use is determined from the filename extension. If a file object was
#'     used instead of a filename, this parameter should always be used.
#' @param scale Whether to rescale image values to be within `[0, 255]`.
#' @param ... Additional keyword arguments passed to `PIL.Image.save()`.
#'
#' @export
#' @seealso
#' + <https://www.tensorflow.org/api_docs/python/tf/keras/preprocessing/image/save_img>
image_array_save <-
function (path, x, data_format = NULL, file_format = NULL, scale = TRUE,
    ...)
{
    args <- capture_args2(NULL)
    do.call(keras$preprocessing$image$save_img, args)
}


# keras$layers$array_to_img
# keras_core.src.utils.image_utils.array_to_img
r"-(Converts a 3D NumPy array to a PIL Image instance.

    Usage:

    ```python
    from PIL import Image
    img = np.random.random(size=(100, 100, 3))
    pil_img = keras.utils.array_to_img(img)
    ```

    Args:
        x: Input data, in any form that can be converted to a NumPy array.
        data_format: Image data format, can be either `"channels_first"` or
            `"channels_last"`. Defaults to `None`, in which case the global
            setting `keras.backend.image_data_format()` is used (unless you
            changed it, it defaults to `"channels_last"`).
        scale: Whether to rescale the image such that minimum and maximum values
            are 0 and 255 respectively. Defaults to `True`.
        dtype: Dtype to use. `None` means the global setting
            `keras.backend.floatx()` is used (unless you changed it, it
            defaults to `"float32"`). Defaults to `None`.

    Returns:
        A PIL Image instance.
    )-"


# keras_core.src.utils.image_utils.array_to_img
#' Converts a 3D NumPy array to a PIL Image instance.
#'
#' @description
#'
#' # Usage
#' ```python
#' from PIL import Image
#' img = np.random.random(size=(100, 100, 3))
#' pil_img = keras.utils.array_to_img(img)
#' ```
#'
#' # Returns
#'     A PIL Image instance.
#'
#' @param x Input data, in any form that can be converted to a NumPy array.
#' @param data_format Image data format, can be either `"channels_first"` or
#'     `"channels_last"`. Defaults to `None`, in which case the global
#'     setting `keras.backend.image_data_format()` is used (unless you
#'     changed it, it defaults to `"channels_last"`).
#' @param scale Whether to rescale the image such that minimum and maximum values
#'     are 0 and 255 respectively. Defaults to `True`.
#' @param dtype Dtype to use. `None` means the global setting
#'     `keras.backend.floatx()` is used (unless you changed it, it
#'     defaults to `"float32"`). Defaults to `None`.
#'
#' @export
#' @seealso
#' + <https://www.tensorflow.org/api_docs/python/tf/keras/preprocessing/image/array_to_img>
image_from_array <-
function (x, data_format = NULL, scale = TRUE, dtype = NULL)
{
    args <- capture_args2(NULL)
    do.call(keras$preprocessing$image$array_to_img, args)
}


# keras$layers$load_img
# keras_core.src.utils.image_utils.load_img
r"-(Loads an image into PIL format.

    Usage:

    ```python
    image = keras.utils.load_img(image_path)
    input_arr = keras.utils.img_to_array(image)
    input_arr = np.array([input_arr])  # Convert single image to a batch.
    predictions = model.predict(input_arr)
    ```

    Args:
        path: Path to image file.
        color_mode: One of `"grayscale"`, `"rgb"`, `"rgba"`. Default: `"rgb"`.
            The desired image format.
        target_size: Either `None` (default to original size) or tuple of ints
            `(img_height, img_width)`.
        interpolation: Interpolation method used to resample the image if the
            target size is different from that of the loaded image. Supported
            methods are `"nearest"`, `"bilinear"`, and `"bicubic"`.
            If PIL version 1.1.3 or newer is installed, `"lanczos"`
            is also supported. If PIL version 3.4.0 or newer is installed,
            `"box"` and `"hamming"` are also
            supported. By default, `"nearest"` is used.
        keep_aspect_ratio: Boolean, whether to resize images to a target
            size without aspect ratio distortion. The image is cropped in
            the center with target aspect ratio before resizing.

    Returns:
        A PIL Image instance.
    )-"


# keras_core.src.utils.image_utils.load_img
#' Loads an image into PIL format.
#'
#' @description
#'
#' # Usage
#' ```python
#' image = keras.utils.load_img(image_path)
#' input_arr = keras.utils.img_to_array(image)
#' input_arr = np.array([input_arr])  # Convert single image to a batch.
#' predictions = model.predict(input_arr)
#' ```
#'
#' # Returns
#'     A PIL Image instance.
#'
#' @param path Path to image file.
#' @param color_mode One of `"grayscale"`, `"rgb"`, `"rgba"`. Default: `"rgb"`.
#'     The desired image format.
#' @param target_size Either `None` (default to original size) or tuple of ints
#'     `(img_height, img_width)`.
#' @param interpolation Interpolation method used to resample the image if the
#'     target size is different from that of the loaded image. Supported
#'     methods are `"nearest"`, `"bilinear"`, and `"bicubic"`.
#'     If PIL version 1.1.3 or newer is installed, `"lanczos"`
#'     is also supported. If PIL version 3.4.0 or newer is installed,
#'     `"box"` and `"hamming"` are also
#'     supported. By default, `"nearest"` is used.
#' @param keep_aspect_ratio Boolean, whether to resize images to a target
#'     size without aspect ratio distortion. The image is cropped in
#'     the center with target aspect ratio before resizing.
#'
#' @export
#' @seealso
#' + <https://www.tensorflow.org/api_docs/python/tf/keras/preprocessing/image/load_img>
image_load <-
function (path, color_mode = "rgb", target_size = NULL, interpolation = "nearest",
    keep_aspect_ratio = FALSE)
{
    args <- capture_args2(NULL)
    do.call(keras$preprocessing$image$load_img, args)
}


# keras$layers$img_to_array
# keras_core.src.utils.image_utils.img_to_array
r"-(Converts a PIL Image instance to a NumPy array.

    Usage:

    ```python
    from PIL import Image
    img_data = np.random.random(size=(100, 100, 3))
    img = keras.utils.array_to_img(img_data)
    array = keras.utils.image.img_to_array(img)
    ```

    Args:
        img: Input PIL Image instance.
        data_format: Image data format, can be either `"channels_first"` or
            `"channels_last"`. Defaults to `None`, in which case the global
            setting `keras.backend.image_data_format()` is used (unless you
            changed it, it defaults to `"channels_last"`).
        dtype: Dtype to use. `None` means the global setting
            `keras.backend.floatx()` is used (unless you changed it, it
            defaults to `"float32"`).

    Returns:
        A 3D NumPy array.
    )-"


# keras_core.src.utils.image_utils.img_to_array
#' Converts a PIL Image instance to a NumPy array.
#'
#' @description
#'
#' # Usage
#' ```python
#' from PIL import Image
#' img_data = np.random.random(size=(100, 100, 3))
#' img = keras.utils.array_to_img(img_data)
#' array = keras.utils.image.img_to_array(img)
#' ```
#'
#' # Returns
#'     A 3D NumPy array.
#'
#' @param img Input PIL Image instance.
#' @param data_format Image data format, can be either `"channels_first"` or
#'     `"channels_last"`. Defaults to `None`, in which case the global
#'     setting `keras.backend.image_data_format()` is used (unless you
#'     changed it, it defaults to `"channels_last"`).
#' @param dtype Dtype to use. `None` means the global setting
#'     `keras.backend.floatx()` is used (unless you changed it, it
#'     defaults to `"float32"`).
#'
#' @export
#' @seealso
#' + <https://www.tensorflow.org/api_docs/python/tf/keras/preprocessing/image/img_to_array>
image_to_array <-
function (img, data_format = NULL, dtype = NULL)
{
    args <- capture_args2(NULL)
    do.call(keras$preprocessing$image$img_to_array, args)
}


# keras$layers$pad_sequences
# keras_core.src.utils.sequence_utils.pad_sequences
r"-(Pads sequences to the same length.

    This function transforms a list (of length `num_samples`)
    of sequences (lists of integers)
    into a 2D NumPy array of shape `(num_samples, num_timesteps)`.
    `num_timesteps` is either the `maxlen` argument if provided,
    or the length of the longest sequence in the list.

    Sequences that are shorter than `num_timesteps`
    are padded with `value` until they are `num_timesteps` long.

    Sequences longer than `num_timesteps` are truncated
    so that they fit the desired length.

    The position where padding or truncation happens is determined by
    the arguments `padding` and `truncating`, respectively.
    Pre-padding or removing values from the beginning of the sequence is the
    default.

    >>> sequence = [[1], [2, 3], [4, 5, 6]]
    >>> keras.utils.pad_sequences(sequence)
    array([[0, 0, 1],
           [0, 2, 3],
           [4, 5, 6]], dtype=int32)

    >>> keras.utils.pad_sequences(sequence, value=-1)
    array([[-1, -1,  1],
           [-1,  2,  3],
           [ 4,  5,  6]], dtype=int32)

    >>> keras.utils.pad_sequences(sequence, padding='post')
    array([[1, 0, 0],
           [2, 3, 0],
           [4, 5, 6]], dtype=int32)

    >>> keras.utils.pad_sequences(sequence, maxlen=2)
    array([[0, 1],
           [2, 3],
           [5, 6]], dtype=int32)

    Args:
        sequences: List of sequences (each sequence is a list of integers).
        maxlen: Optional Int, maximum length of all sequences. If not provided,
            sequences will be padded to the length of the longest individual
            sequence.
        dtype: (Optional, defaults to `"int32"`). Type of the output sequences.
            To pad sequences with variable length strings, you can use `object`.
        padding: String, "pre" or "post" (optional, defaults to `"pre"`):
            pad either before or after each sequence.
        truncating: String, "pre" or "post" (optional, defaults to `"pre"`):
            remove values from sequences larger than
            `maxlen`, either at the beginning or at the end of the sequences.
        value: Float or String, padding value. (Optional, defaults to 0.)

    Returns:
        NumPy array with shape `(len(sequences), maxlen)`
    )-"


# keras_core.src.utils.sequence_utils.pad_sequences
#' Pads sequences to the same length.
#'
#' @description
#' This function transforms a list (of length `num_samples`)
#' of sequences (lists of integers)
#' into a 2D NumPy array of shape `(num_samples, num_timesteps)`.
#' `num_timesteps` is either the `maxlen` argument if provided,
#' or the length of the longest sequence in the list.
#'
#' Sequences that are shorter than `num_timesteps`
#' are padded with `value` until they are `num_timesteps` long.
#'
#' Sequences longer than `num_timesteps` are truncated
#' so that they fit the desired length.
#'
#' The position where padding or truncation happens is determined by
#' the arguments `padding` and `truncating`, respectively.
#' Pre-padding or removing values from the beginning of the sequence is the
#' default.
#'
#' ```python
#' sequence = [[1], [2, 3], [4, 5, 6]]
#' keras.utils.pad_sequences(sequence)
#' # array([[0, 0, 1],
#' #        [0, 2, 3],
#' #        [4, 5, 6]], dtype=int32)
#' ```
#'
#' ```python
#' keras.utils.pad_sequences(sequence, value=-1)
#' # array([[-1, -1,  1],
#' #        [-1,  2,  3],
#' #        [ 4,  5,  6]], dtype=int32)
#' ```
#'
#' ```python
#' keras.utils.pad_sequences(sequence, padding='post')
#' # array([[1, 0, 0],
#' #        [2, 3, 0],
#' #        [4, 5, 6]], dtype=int32)
#' ```
#'
#' ```python
#' keras.utils.pad_sequences(sequence, maxlen=2)
#' # array([[0, 1],
#' #        [2, 3],
#' #        [5, 6]], dtype=int32)
#' ```
#'
#' # Returns
#'     NumPy array with shape `(len(sequences), maxlen)`
#'
#' @param sequences List of sequences (each sequence is a list of integers).
#' @param maxlen Optional Int, maximum length of all sequences. If not provided,
#'     sequences will be padded to the length of the longest individual
#'     sequence.
#' @param dtype (Optional, defaults to `"int32"`). Type of the output sequences.
#'     To pad sequences with variable length strings, you can use `object`.
#' @param padding String, "pre" or "post" (optional, defaults to `"pre"`):
#'     pad either before or after each sequence.
#' @param truncating String, "pre" or "post" (optional, defaults to `"pre"`):
#'     remove values from sequences larger than
#'     `maxlen`, either at the beginning or at the end of the sequences.
#' @param value Float or String, padding value. (Optional, defaults to 0.)
#'
#' @export
#' @seealso
#' + <https://www.tensorflow.org/api_docs/python/tf/keras/preprocessing/sequence/pad_sequences>
pad_sequences <-
function (sequences, maxlen = NULL, dtype = "int32", padding = "pre",
    truncating = "pre", value = 0)
{
    args <- capture_args2(list(maxlen = as_integer))
    do.call(keras$preprocessing$sequence$pad_sequences, args)
}


# keras$layers$text_dataset_from_directory
# keras_core.src.utils.text_dataset_utils.text_dataset_from_directory
r"-(Generates a `tf.data.Dataset` from text files in a directory.

    If your directory structure is:

    ```
    main_directory/
    ...class_a/
    ......a_text_1.txt
    ......a_text_2.txt
    ...class_b/
    ......b_text_1.txt
    ......b_text_2.txt
    ```

    Then calling `text_dataset_from_directory(main_directory,
    labels='inferred')` will return a `tf.data.Dataset` that yields batches of
    texts from the subdirectories `class_a` and `class_b`, together with labels
    0 and 1 (0 corresponding to `class_a` and 1 corresponding to `class_b`).

    Only `.txt` files are supported at this time.

    Args:
        directory: Directory where the data is located.
            If `labels` is `"inferred"`, it should contain
            subdirectories, each containing text files for a class.
            Otherwise, the directory structure is ignored.
        labels: Either `"inferred"`
            (labels are generated from the directory structure),
            `None` (no labels),
            or a list/tuple of integer labels of the same size as the number of
            text files found in the directory. Labels should be sorted according
            to the alphanumeric order of the text file paths
            (obtained via `os.walk(directory)` in Python).
        label_mode: String describing the encoding of `labels`. Options are:
            - `"int"`: means that the labels are encoded as integers
                (e.g. for `sparse_categorical_crossentropy` loss).
            - `"categorical"` means that the labels are
                encoded as a categorical vector
                (e.g. for `categorical_crossentropy` loss).
            - `"binary"` means that the labels (there can be only 2)
                are encoded as `float32` scalars with values 0 or 1
                (e.g. for `binary_crossentropy`).
            - `None` (no labels).
        class_names: Only valid if `"labels"` is `"inferred"`.
            This is the explicit list of class names
            (must match names of subdirectories). Used to control the order
            of the classes (otherwise alphanumerical order is used).
        batch_size: Size of the batches of data. Defaults to 32.
            If `None`, the data will not be batched
            (the dataset will yield individual samples).
        max_length: Maximum size of a text string. Texts longer than this will
            be truncated to `max_length`.
        shuffle: Whether to shuffle the data. Defaults to `True`.
            If set to `False`, sorts the data in alphanumeric order.
        seed: Optional random seed for shuffling and transformations.
        validation_split: Optional float between 0 and 1,
            fraction of data to reserve for validation.
        subset: Subset of the data to return.
            One of `"training"`, `"validation"` or `"both"`.
            Only used if `validation_split` is set.
            When `subset="both"`, the utility returns a tuple of two datasets
            (the training and validation datasets respectively).
        follow_links: Whether to visits subdirectories pointed to by symlinks.
            Defaults to `False`.

    Returns:

    A `tf.data.Dataset` object.

    - If `label_mode` is `None`, it yields `string` tensors of shape
        `(batch_size,)`, containing the contents of a batch of text files.
    - Otherwise, it yields a tuple `(texts, labels)`, where `texts`
        has shape `(batch_size,)` and `labels` follows the format described
        below.

    Rules regarding labels format:

    - if `label_mode` is `int`, the labels are an `int32` tensor of shape
        `(batch_size,)`.
    - if `label_mode` is `binary`, the labels are a `float32` tensor of
        1s and 0s of shape `(batch_size, 1)`.
    - if `label_mode` is `categorical`, the labels are a `float32` tensor
        of shape `(batch_size, num_classes)`, representing a one-hot
        encoding of the class index.
    )-"


# keras_core.src.utils.text_dataset_utils.text_dataset_from_directory
#' Generates a `tf.data.Dataset` from text files in a directory.
#'
#' @description
#' If your directory structure is:
#'
#' ```
#' main_directory/
#' ...class_a/
#' ......a_text_1.txt
#' ......a_text_2.txt
#' ...class_b/
#' ......b_text_1.txt
#' ......b_text_2.txt
#' ```
#'
#' Then calling `text_dataset_from_directory(main_directory,
#' labels='inferred')` will return a `tf.data.Dataset` that yields batches of
#' texts from the subdirectories `class_a` and `class_b`, together with labels
#' 0 and 1 (0 corresponding to `class_a` and 1 corresponding to `class_b`).
#'
#' Only `.txt` files are supported at this time.
#'
#' # Returns
#' A `tf.data.Dataset` object.
#'
#' - If `label_mode` is `None`, it yields `string` tensors of shape
#'     `(batch_size,)`, containing the contents of a batch of text files.
#' - Otherwise, it yields a tuple `(texts, labels)`, where `texts`
#'     has shape `(batch_size,)` and `labels` follows the format described
#'     below.
#'
#' Rules regarding labels format:
#'
#' - if `label_mode` is `int`, the labels are an `int32` tensor of shape
#'     `(batch_size,)`.
#' - if `label_mode` is `binary`, the labels are a `float32` tensor of
#'     1s and 0s of shape `(batch_size, 1)`.
#' - if `label_mode` is `categorical`, the labels are a `float32` tensor
#'     of shape `(batch_size, num_classes)`, representing a one-hot
#'     encoding of the class index.
#'
#' @param directory Directory where the data is located.
#'     If `labels` is `"inferred"`, it should contain
#'     subdirectories, each containing text files for a class.
#'     Otherwise, the directory structure is ignored.
#' @param labels Either `"inferred"`
#'     (labels are generated from the directory structure),
#'     `None` (no labels),
#'     or a list/tuple of integer labels of the same size as the number of
#'     text files found in the directory. Labels should be sorted according
#'     to the alphanumeric order of the text file paths
#'     (obtained via `os.walk(directory)` in Python).
#' @param label_mode String describing the encoding of `labels`. Options are:
#'     - `"int"`: means that the labels are encoded as integers
#'         (e.g. for `sparse_categorical_crossentropy` loss).
#'     - `"categorical"` means that the labels are
#'         encoded as a categorical vector
#'         (e.g. for `categorical_crossentropy` loss).
#'     - `"binary"` means that the labels (there can be only 2)
#'         are encoded as `float32` scalars with values 0 or 1
#'         (e.g. for `binary_crossentropy`).
#'     - `None` (no labels).
#' @param class_names Only valid if `"labels"` is `"inferred"`.
#'     This is the explicit list of class names
#'     (must match names of subdirectories). Used to control the order
#'     of the classes (otherwise alphanumerical order is used).
#' @param batch_size Size of the batches of data. Defaults to 32.
#'     If `None`, the data will not be batched
#'     (the dataset will yield individual samples).
#' @param max_length Maximum size of a text string. Texts longer than this will
#'     be truncated to `max_length`.
#' @param shuffle Whether to shuffle the data. Defaults to `True`.
#'     If set to `False`, sorts the data in alphanumeric order.
#' @param seed Optional random seed for shuffling and transformations.
#' @param validation_split Optional float between 0 and 1,
#'     fraction of data to reserve for validation.
#' @param subset Subset of the data to return.
#'     One of `"training"`, `"validation"` or `"both"`.
#'     Only used if `validation_split` is set.
#'     When `subset="both"`, the utility returns a tuple of two datasets
#'     (the training and validation datasets respectively).
#' @param follow_links Whether to visits subdirectories pointed to by symlinks.
#'     Defaults to `False`.
#'
#' @export
#' @seealso
#' + <https://www.tensorflow.org/api_docs/python/tf/keras/preprocessing/text_dataset_from_directory>
text_dataset_from_directory <-
function (directory, labels = "inferred", label_mode = "int",
    class_names = NULL, batch_size = 32L, max_length = NULL,
    shuffle = TRUE, seed = NULL, validation_split = NULL, subset = NULL,
    follow_links = FALSE)
{
    args <- capture_args2(list(labels = as_integer, label_mode = as_integer,
        batch_size = as_integer))
    do.call(keras$preprocessing$text_dataset_from_directory,
        args)
}


# keras$layers$timeseries_dataset_from_array
# keras_core.src.utils.timeseries_dataset_utils.timeseries_dataset_from_array
r"-(Creates a dataset of sliding windows over a timeseries provided as array.

    This function takes in a sequence of data-points gathered at
    equal intervals, along with time series parameters such as
    length of the sequences/windows, spacing between two sequence/windows, etc.,
    to produce batches of timeseries inputs and targets.

    Args:
        data: Numpy array or eager tensor
            containing consecutive data points (timesteps).
            Axis 0 is expected to be the time dimension.
        targets: Targets corresponding to timesteps in `data`.
            `targets[i]` should be the target
            corresponding to the window that starts at index `i`
            (see example 2 below).
            Pass `None` if you don't have target data (in this case the dataset
            will only yield the input data).
        sequence_length: Length of the output sequences
            (in number of timesteps).
        sequence_stride: Period between successive output sequences.
            For stride `s`, output samples would
            start at index `data[i]`, `data[i + s]`, `data[i + 2 * s]`, etc.
        sampling_rate: Period between successive individual timesteps
            within sequences. For rate `r`, timesteps
            `data[i], data[i + r], ... data[i + sequence_length]`
            are used for creating a sample sequence.
        batch_size: Number of timeseries samples in each batch
            (except maybe the last one). If `None`, the data will not be batched
            (the dataset will yield individual samples).
        shuffle: Whether to shuffle output samples,
            or instead draw them in chronological order.
        seed: Optional int; random seed for shuffling.
        start_index: Optional int; data points earlier (exclusive)
            than `start_index` will not be used
            in the output sequences. This is useful to reserve part of the
            data for test or validation.
        end_index: Optional int; data points later (exclusive) than `end_index`
            will not be used in the output sequences.
            This is useful to reserve part of the data for test or validation.

    Returns:

    A `tf.data.Dataset` instance. If `targets` was passed, the dataset yields
    tuple `(batch_of_sequences, batch_of_targets)`. If not, the dataset yields
    only `batch_of_sequences`.

    Example 1:

    Consider indices `[0, 1, ... 98]`.
    With `sequence_length=10,  sampling_rate=2, sequence_stride=3`,
    `shuffle=False`, the dataset will yield batches of sequences
    composed of the following indices:

    ```
    First sequence:  [0  2  4  6  8 10 12 14 16 18]
    Second sequence: [3  5  7  9 11 13 15 17 19 21]
    Third sequence:  [6  8 10 12 14 16 18 20 22 24]
    ...
    Last sequence:   [78 80 82 84 86 88 90 92 94 96]
    ```

    In this case the last 2 data points are discarded since no full sequence
    can be generated to include them (the next sequence would have started
    at index 81, and thus its last step would have gone over 98).

    Example 2: Temporal regression.

    Consider an array `data` of scalar values, of shape `(steps,)`.
    To generate a dataset that uses the past 10
    timesteps to predict the next timestep, you would use:

    ```python
    input_data = data[:-10]
    targets = data[10:]
    dataset = timeseries_dataset_from_array(
        input_data, targets, sequence_length=10)
    for batch in dataset:
      inputs, targets = batch
      assert np.array_equal(inputs[0], data[:10])  # First sequence: steps [0-9]
      # Corresponding target: step 10
      assert np.array_equal(targets[0], data[10])
      break
    ```

    Example 3: Temporal regression for many-to-many architectures.

    Consider two arrays of scalar values `X` and `Y`,
    both of shape `(100,)`. The resulting dataset should consist samples with
    20 timestamps each. The samples should not overlap.
    To generate a dataset that uses the current timestamp
    to predict the corresponding target timestep, you would use:

    ```python
    X = np.arange(100)
    Y = X*2

    sample_length = 20
    input_dataset = timeseries_dataset_from_array(
        X, None, sequence_length=sample_length, sequence_stride=sample_length)
    target_dataset = timeseries_dataset_from_array(
        Y, None, sequence_length=sample_length, sequence_stride=sample_length)

    for batch in zip(input_dataset, target_dataset):
        inputs, targets = batch
        assert np.array_equal(inputs[0], X[:sample_length])

        # second sample equals output timestamps 20-40
        assert np.array_equal(targets[1], Y[sample_length:2*sample_length])
        break
    ```
    )-"


# keras_core.src.utils.timeseries_dataset_utils.timeseries_dataset_from_array
#' Creates a dataset of sliding windows over a timeseries provided as array.
#'
#' @description
#' This function takes in a sequence of data-points gathered at
#' equal intervals, along with time series parameters such as
#' length of the sequences/windows, spacing between two sequence/windows, etc.,
#' to produce batches of timeseries inputs and targets.
#'
#' # Returns
#' A `tf.data.Dataset` instance. If `targets` was passed, the dataset yields
#' tuple `(batch_of_sequences, batch_of_targets)`. If not, the dataset yields
#' only `batch_of_sequences`.
#'
#' Example 1:
#'
#' Consider indices `[0, 1, ... 98]`.
#' With `sequence_length=10,  sampling_rate=2, sequence_stride=3`,
#' `shuffle=False`, the dataset will yield batches of sequences
#' composed of the following indices:
#'
#' ```
#' First sequence:  [0  2  4  6  8 10 12 14 16 18]
#' Second sequence: [3  5  7  9 11 13 15 17 19 21]
#' Third sequence:  [6  8 10 12 14 16 18 20 22 24]
#' ...
#' Last sequence:   [78 80 82 84 86 88 90 92 94 96]
#' ```
#'
#' In this case the last 2 data points are discarded since no full sequence
#' can be generated to include them (the next sequence would have started
#' at index 81, and thus its last step would have gone over 98).
#'
#' Example 2: Temporal regression.
#'
#' Consider an array `data` of scalar values, of shape `(steps,)`.
#' To generate a dataset that uses the past 10
#' timesteps to predict the next timestep, you would use:
#'
#' ```python
#' input_data = data[:-10]
#' targets = data[10:]
#' dataset = timeseries_dataset_from_array(
#'     input_data, targets, sequence_length=10)
#' for batch in dataset:
#'   inputs, targets = batch
#'   assert np.array_equal(inputs[0], data[:10])  # First sequence: steps [0-9]
#'   # Corresponding target: step 10
#'   assert np.array_equal(targets[0], data[10])
#'   break
#' ```
#'
#' Example 3: Temporal regression for many-to-many architectures.
#'
#' Consider two arrays of scalar values `X` and `Y`,
#' both of shape `(100,)`. The resulting dataset should consist samples with
#' 20 timestamps each. The samples should not overlap.
#' To generate a dataset that uses the current timestamp
#' to predict the corresponding target timestep, you would use:
#'
#' ```python
#' X = np.arange(100)
#' Y = X*2
#'
#' sample_length = 20
#' input_dataset = timeseries_dataset_from_array(
#'     X, None, sequence_length=sample_length, sequence_stride=sample_length)
#' target_dataset = timeseries_dataset_from_array(
#'     Y, None, sequence_length=sample_length, sequence_stride=sample_length)
#'
#' for batch in zip(input_dataset, target_dataset):
#'     inputs, targets = batch
#'     assert np.array_equal(inputs[0], X[:sample_length])
#'
#'     # second sample equals output timestamps 20-40
#'     assert np.array_equal(targets[1], Y[sample_length:2*sample_length])
#'     break
#' ```
#'
#' @param data Numpy array or eager tensor
#'     containing consecutive data points (timesteps).
#'     Axis 0 is expected to be the time dimension.
#' @param targets Targets corresponding to timesteps in `data`.
#'     `targets[i]` should be the target
#'     corresponding to the window that starts at index `i`
#'     (see example 2 below).
#'     Pass `None` if you don't have target data (in this case the dataset
#'     will only yield the input data).
#' @param sequence_length Length of the output sequences
#'     (in number of timesteps).
#' @param sequence_stride Period between successive output sequences.
#'     For stride `s`, output samples would
#'     start at index `data[i]`, `data[i + s]`, `data[i + 2 * s]`, etc.
#' @param sampling_rate Period between successive individual timesteps
#'     within sequences. For rate `r`, timesteps
#'     `data[i], data[i + r], ... data[i + sequence_length]`
#'     are used for creating a sample sequence.
#' @param batch_size Number of timeseries samples in each batch
#'     (except maybe the last one). If `None`, the data will not be batched
#'     (the dataset will yield individual samples).
#' @param shuffle Whether to shuffle output samples,
#'     or instead draw them in chronological order.
#' @param seed Optional int; random seed for shuffling.
#' @param start_index Optional int; data points earlier (exclusive)
#'     than `start_index` will not be used
#'     in the output sequences. This is useful to reserve part of the
#'     data for test or validation.
#' @param end_index Optional int; data points later (exclusive) than `end_index`
#'     will not be used in the output sequences.
#'     This is useful to reserve part of the data for test or validation.
#'
#' @export
#' @seealso
#' + <https://www.tensorflow.org/api_docs/python/tf/keras/preprocessing/timeseries_dataset_from_array>
timeseries_dataset_from_array <-
function (data, targets, sequence_length, sequence_stride = 1L,
    sampling_rate = 1L, batch_size = 128L, shuffle = FALSE, seed = NULL,
    start_index = NULL, end_index = NULL)
{
    args <- capture_args2(list(sequence_stride = as_integer,
        sampling_rate = as_integer, batch_size = as_integer,
        seed = as_integer, start_index = as_integer, end_index = as_integer))
    do.call(keras$preprocessing$timeseries_dataset_from_array,
        args)
}
