## Autogenerated. Do not modify manually.


"man-src/metric_binary_focal_crossentropy.Rmd" # |>file.edit() # or cmd+click to edit man page
"man-src/metric_binary_focal_crossentropy/0-upstream.md" # view the upstream doc
#' @eval readLines("man-src/metric_binary_focal_crossentropy/3-rendered.md")
metric_binary_focal_crossentropy <-
function (y_true, y_pred, apply_class_balancing = FALSE, alpha = 0.25,
    gamma = 2, from_logits = FALSE, label_smoothing = 0, axis = -1L)
{
    args <- capture_args2(list(axis = as_axis))
    do.call(keras$metrics$binary_focal_crossentropy, args)
}


"man-src/metric_categorical_focal_crossentropy.Rmd" # |>file.edit() # or cmd+click to edit man page
"man-src/metric_categorical_focal_crossentropy/0-upstream.md" # view the upstream doc
#' @eval readLines("man-src/metric_categorical_focal_crossentropy/3-rendered.md")
metric_categorical_focal_crossentropy <-
function (y_true, y_pred, alpha = 0.25, gamma = 2, from_logits = FALSE,
    label_smoothing = 0, axis = -1L)
{
    args <- capture_args2(list(axis = as_axis))
    do.call(keras$metrics$categorical_focal_crossentropy, args)
}


"man-src/metric_huber.Rmd" # |>file.edit() # or cmd+click to edit man page
"man-src/metric_huber/0-upstream.md" # view the upstream doc
#' @eval readLines("man-src/metric_huber/3-rendered.md")
metric_huber <-
function (y_true, y_pred, delta = 1)
{
    args <- capture_args2(NULL)
    do.call(keras$metrics$huber, args)
}


"man-src/metric_log_cosh.Rmd" # |>file.edit() # or cmd+click to edit man page
"man-src/metric_log_cosh/0-upstream.md" # view the upstream doc
#' @eval readLines("man-src/metric_log_cosh/3-rendered.md")
metric_log_cosh <-
function (y_true, y_pred)
{
    args <- capture_args2(NULL)
    do.call(keras$metrics$log_cosh, args)
}


"man-src/metric_binary_accuracy.Rmd" # |>file.edit() # or cmd+click to edit man page
"man-src/metric_binary_accuracy/0-upstream.md" # view the upstream doc
#' @eval readLines("man-src/metric_binary_accuracy/3-rendered.md")
metric_binary_accuracy <-
structure(function (y_true, y_pred, threshold = 0.5, ..., name = "binary_accuracy",
    dtype = NULL)
{
    args <- capture_args2(NULL)
    callable <- if (missing(y_true) && missing(y_pred))
        keras$metrics$BinaryAccuracy
    else keras$metrics$binary_accuracy
    do.call(callable, args)
}, py_function_name = "binary_accuracy")


"man-src/metric_categorical_accuracy.Rmd" # |>file.edit() # or cmd+click to edit man page
"man-src/metric_categorical_accuracy/0-upstream.md" # view the upstream doc
#' @eval readLines("man-src/metric_categorical_accuracy/3-rendered.md")
metric_categorical_accuracy <-
structure(function (y_true, y_pred, ..., name = "categorical_accuracy",
    dtype = NULL)
{
    args <- capture_args2(NULL)
    callable <- if (missing(y_true) && missing(y_pred))
        keras$metrics$CategoricalAccuracy
    else keras$metrics$categorical_accuracy
    do.call(callable, args)
}, py_function_name = "categorical_accuracy")


"man-src/metric_sparse_categorical_accuracy.Rmd" # |>file.edit() # or cmd+click to edit man page
"man-src/metric_sparse_categorical_accuracy/0-upstream.md" # view the upstream doc
#' @eval readLines("man-src/metric_sparse_categorical_accuracy/3-rendered.md")
metric_sparse_categorical_accuracy <-
structure(function (y_true, y_pred, ..., name = "sparse_categorical_accuracy",
    dtype = NULL)
{
    args <- capture_args2(NULL)
    callable <- if (missing(y_true) && missing(y_pred))
        keras$metrics$SparseCategoricalAccuracy
    else keras$metrics$sparse_categorical_accuracy
    do.call(callable, args)
}, py_function_name = "sparse_categorical_accuracy")


"man-src/metric_sparse_top_k_categorical_accuracy.Rmd" # |>file.edit() # or cmd+click to edit man page
"man-src/metric_sparse_top_k_categorical_accuracy/0-upstream.md" # view the upstream doc
#' @eval readLines("man-src/metric_sparse_top_k_categorical_accuracy/3-rendered.md")
metric_sparse_top_k_categorical_accuracy <-
structure(function (y_true, y_pred, k = 5L, ..., name = "sparse_top_k_categorical_accuracy",
    dtype = NULL)
{
    args <- capture_args2(list(k = as_integer))
    callable <- if (missing(y_true) && missing(y_pred))
        keras$metrics$SparseTopKCategoricalAccuracy
    else keras$metrics$sparse_top_k_categorical_accuracy
    do.call(callable, args)
}, py_function_name = "sparse_top_k_categorical_accuracy")


"man-src/metric_top_k_categorical_accuracy.Rmd" # |>file.edit() # or cmd+click to edit man page
"man-src/metric_top_k_categorical_accuracy/0-upstream.md" # view the upstream doc
#' @eval readLines("man-src/metric_top_k_categorical_accuracy/3-rendered.md")
metric_top_k_categorical_accuracy <-
structure(function (y_true, y_pred, k = 5L, ..., name = "top_k_categorical_accuracy",
    dtype = NULL)
{
    args <- capture_args2(list(k = as_integer))
    callable <- if (missing(y_true) && missing(y_pred))
        keras$metrics$TopKCategoricalAccuracy
    else keras$metrics$top_k_categorical_accuracy
    do.call(callable, args)
}, py_function_name = "top_k_categorical_accuracy")


"man-src/metric_auc.Rmd" # |>file.edit() # or cmd+click to edit man page
"man-src/metric_auc/0-upstream.md" # view the upstream doc
#' @eval readLines("man-src/metric_auc/3-rendered.md")
metric_auc <-
function (..., num_thresholds = 200L, curve = "ROC", summation_method = "interpolation",
    name = NULL, dtype = NULL, thresholds = NULL, multi_label = FALSE,
    num_labels = NULL, label_weights = NULL, from_logits = FALSE)
{
    args <- capture_args2(list(num_thresholds = as_integer))
    do.call(keras$metrics$AUC, args)
}


"man-src/metric_false_negatives.Rmd" # |>file.edit() # or cmd+click to edit man page
"man-src/metric_false_negatives/0-upstream.md" # view the upstream doc
#' @eval readLines("man-src/metric_false_negatives/3-rendered.md")
metric_false_negatives <-
function (..., thresholds = NULL, name = NULL, dtype = NULL)
{
    args <- capture_args2(NULL)
    do.call(keras$metrics$FalseNegatives, args)
}


"man-src/metric_false_positives.Rmd" # |>file.edit() # or cmd+click to edit man page
"man-src/metric_false_positives/0-upstream.md" # view the upstream doc
#' @eval readLines("man-src/metric_false_positives/3-rendered.md")
metric_false_positives <-
function (..., thresholds = NULL, name = NULL, dtype = NULL)
{
    args <- capture_args2(NULL)
    do.call(keras$metrics$FalsePositives, args)
}


"man-src/metric_precision.Rmd" # |>file.edit() # or cmd+click to edit man page
"man-src/metric_precision/0-upstream.md" # view the upstream doc
#' @eval readLines("man-src/metric_precision/3-rendered.md")
metric_precision <-
function (..., thresholds = NULL, top_k = NULL, class_id = NULL,
    name = NULL, dtype = NULL)
{
    args <- capture_args2(list(top_k = as_integer, class_id = as_integer))
    do.call(keras$metrics$Precision, args)
}


"man-src/metric_precision_at_recall.Rmd" # |>file.edit() # or cmd+click to edit man page
"man-src/metric_precision_at_recall/0-upstream.md" # view the upstream doc
#' @eval readLines("man-src/metric_precision_at_recall/3-rendered.md")
metric_precision_at_recall <-
function (..., recall, num_thresholds = 200L, class_id = NULL,
    name = NULL, dtype = NULL)
{
    args <- capture_args2(list(num_thresholds = as_integer, class_id = as_integer))
    do.call(keras$metrics$PrecisionAtRecall, args)
}


"man-src/metric_recall.Rmd" # |>file.edit() # or cmd+click to edit man page
"man-src/metric_recall/0-upstream.md" # view the upstream doc
#' @eval readLines("man-src/metric_recall/3-rendered.md")
metric_recall <-
function (..., thresholds = NULL, top_k = NULL, class_id = NULL,
    name = NULL, dtype = NULL)
{
    args <- capture_args2(list(top_k = as_integer, class_id = as_integer))
    do.call(keras$metrics$Recall, args)
}


"man-src/metric_recall_at_precision.Rmd" # |>file.edit() # or cmd+click to edit man page
"man-src/metric_recall_at_precision/0-upstream.md" # view the upstream doc
#' @eval readLines("man-src/metric_recall_at_precision/3-rendered.md")
metric_recall_at_precision <-
function (..., precision, num_thresholds = 200L, class_id = NULL,
    name = NULL, dtype = NULL)
{
    args <- capture_args2(list(num_thresholds = as_integer, class_id = as_integer))
    do.call(keras$metrics$RecallAtPrecision, args)
}


"man-src/metric_sensitivity_at_specificity.Rmd" # |>file.edit() # or cmd+click to edit man page
"man-src/metric_sensitivity_at_specificity/0-upstream.md" # view the upstream doc
#' @eval readLines("man-src/metric_sensitivity_at_specificity/3-rendered.md")
metric_sensitivity_at_specificity <-
function (..., specificity, num_thresholds = 200L, class_id = NULL,
    name = NULL, dtype = NULL)
{
    args <- capture_args2(list(num_thresholds = as_integer, class_id = as_integer))
    do.call(keras$metrics$SensitivityAtSpecificity, args)
}


"man-src/metric_specificity_at_sensitivity.Rmd" # |>file.edit() # or cmd+click to edit man page
"man-src/metric_specificity_at_sensitivity/0-upstream.md" # view the upstream doc
#' @eval readLines("man-src/metric_specificity_at_sensitivity/3-rendered.md")
metric_specificity_at_sensitivity <-
function (..., sensitivity, num_thresholds = 200L, class_id = NULL,
    name = NULL, dtype = NULL)
{
    args <- capture_args2(list(num_thresholds = as_integer, class_id = as_integer))
    do.call(keras$metrics$SpecificityAtSensitivity, args)
}


"man-src/metric_true_negatives.Rmd" # |>file.edit() # or cmd+click to edit man page
"man-src/metric_true_negatives/0-upstream.md" # view the upstream doc
#' @eval readLines("man-src/metric_true_negatives/3-rendered.md")
metric_true_negatives <-
function (..., thresholds = NULL, name = NULL, dtype = NULL)
{
    args <- capture_args2(NULL)
    do.call(keras$metrics$TrueNegatives, args)
}


"man-src/metric_true_positives.Rmd" # |>file.edit() # or cmd+click to edit man page
"man-src/metric_true_positives/0-upstream.md" # view the upstream doc
#' @eval readLines("man-src/metric_true_positives/3-rendered.md")
metric_true_positives <-
function (..., thresholds = NULL, name = NULL, dtype = NULL)
{
    args <- capture_args2(NULL)
    do.call(keras$metrics$TruePositives, args)
}


"man-src/metric_f1_score.Rmd" # |>file.edit() # or cmd+click to edit man page
"man-src/metric_f1_score/0-upstream.md" # view the upstream doc
#' @eval readLines("man-src/metric_f1_score/3-rendered.md")
metric_f1_score <-
function (..., average = NULL, threshold = NULL, name = "f1_score",
    dtype = NULL)
{
    args <- capture_args2(NULL)
    do.call(keras$metrics$F1Score, args)
}


"man-src/metric_fbeta_score.Rmd" # |>file.edit() # or cmd+click to edit man page
"man-src/metric_fbeta_score/0-upstream.md" # view the upstream doc
#' @eval readLines("man-src/metric_fbeta_score/3-rendered.md")
metric_fbeta_score <-
function (..., average = NULL, beta = 1, threshold = NULL, name = "fbeta_score",
    dtype = NULL)
{
    args <- capture_args2(NULL)
    do.call(keras$metrics$FBetaScore, args)
}


"man-src/metric_categorical_hinge.Rmd" # |>file.edit() # or cmd+click to edit man page
"man-src/metric_categorical_hinge/0-upstream.md" # view the upstream doc
#' @eval readLines("man-src/metric_categorical_hinge/3-rendered.md")
metric_categorical_hinge <-
structure(function (y_true, y_pred, ..., name = "categorical_hinge",
    dtype = NULL)
{
    args <- capture_args2(NULL)
    callable <- if (missing(y_true) && missing(y_pred))
        keras$metrics$CategoricalHinge
    else keras$metrics$categorical_hinge
    do.call(callable, args)
}, py_function_name = "categorical_hinge")


"man-src/metric_hinge.Rmd" # |>file.edit() # or cmd+click to edit man page
"man-src/metric_hinge/0-upstream.md" # view the upstream doc
#' @eval readLines("man-src/metric_hinge/3-rendered.md")
metric_hinge <-
structure(function (y_true, y_pred, ..., name = "hinge", dtype = NULL)
{
    args <- capture_args2(NULL)
    callable <- if (missing(y_true) && missing(y_pred))
        keras$metrics$Hinge
    else keras$metrics$hinge
    do.call(callable, args)
}, py_function_name = "hinge")


"man-src/metric_squared_hinge.Rmd" # |>file.edit() # or cmd+click to edit man page
"man-src/metric_squared_hinge/0-upstream.md" # view the upstream doc
#' @eval readLines("man-src/metric_squared_hinge/3-rendered.md")
metric_squared_hinge <-
structure(function (y_true, y_pred, ..., name = "squared_hinge",
    dtype = NULL)
{
    args <- capture_args2(NULL)
    callable <- if (missing(y_true) && missing(y_pred))
        keras$metrics$SquaredHinge
    else keras$metrics$squared_hinge
    do.call(callable, args)
}, py_function_name = "squared_hinge")


"man-src/metric_binary_iou.Rmd" # |>file.edit() # or cmd+click to edit man page
"man-src/metric_binary_iou/0-upstream.md" # view the upstream doc
#' @eval readLines("man-src/metric_binary_iou/3-rendered.md")
metric_binary_iou <-
function (..., target_class_ids = list(0L, 1L), threshold = 0.5,
    name = NULL, dtype = NULL)
{
    args <- capture_args2(NULL)
    do.call(keras$metrics$BinaryIoU, args)
}


"man-src/metric_iou.Rmd" # |>file.edit() # or cmd+click to edit man page
"man-src/metric_iou/0-upstream.md" # view the upstream doc
#' @eval readLines("man-src/metric_iou/3-rendered.md")
metric_iou <-
function (..., num_classes, target_class_ids, name = NULL, dtype = NULL,
    ignore_class = NULL, sparse_y_true = TRUE, sparse_y_pred = TRUE,
    axis = -1L)
{
    args <- capture_args2(list(ignore_class = as_integer, axis = as_axis))
    do.call(keras$metrics$IoU, args)
}


"man-src/metric_mean_iou.Rmd" # |>file.edit() # or cmd+click to edit man page
"man-src/metric_mean_iou/0-upstream.md" # view the upstream doc
#' @eval readLines("man-src/metric_mean_iou/3-rendered.md")
metric_mean_iou <-
function (..., num_classes, name = NULL, dtype = NULL, ignore_class = NULL,
    sparse_y_true = TRUE, sparse_y_pred = TRUE, axis = -1L)
{
    args <- capture_args2(list(ignore_class = as_integer, axis = as_axis))
    do.call(keras$metrics$MeanIoU, args)
}


"man-src/metric_one_hot_iou.Rmd" # |>file.edit() # or cmd+click to edit man page
"man-src/metric_one_hot_iou/0-upstream.md" # view the upstream doc
#' @eval readLines("man-src/metric_one_hot_iou/3-rendered.md")
metric_one_hot_iou <-
function (..., num_classes, target_class_ids, name = NULL, dtype = NULL,
    ignore_class = NULL, sparse_y_pred = FALSE, axis = -1L)
{
    args <- capture_args2(list(ignore_class = as_integer, axis = as_axis))
    do.call(keras$metrics$OneHotIoU, args)
}


"man-src/metric_one_hot_mean_iou.Rmd" # |>file.edit() # or cmd+click to edit man page
"man-src/metric_one_hot_mean_iou/0-upstream.md" # view the upstream doc
#' @eval readLines("man-src/metric_one_hot_mean_iou/3-rendered.md")
metric_one_hot_mean_iou <-
function (..., num_classes, name = NULL, dtype = NULL, ignore_class = NULL,
    sparse_y_pred = FALSE, axis = -1L)
{
    args <- capture_args2(list(ignore_class = as_integer, axis = as_axis))
    do.call(keras$metrics$OneHotMeanIoU, args)
}


"man-src/metric_binary_crossentropy.Rmd" # |>file.edit() # or cmd+click to edit man page
"man-src/metric_binary_crossentropy/0-upstream.md" # view the upstream doc
#' @eval readLines("man-src/metric_binary_crossentropy/3-rendered.md")
metric_binary_crossentropy <-
structure(function (y_true, y_pred, from_logits = FALSE, label_smoothing = 0,
    axis = -1L, ..., name = "binary_crossentropy", dtype = NULL)
{
    args <- capture_args2(list(label_smoothing = as_integer,
        axis = as_axis))
    callable <- if (missing(y_true) && missing(y_pred))
        keras$metrics$BinaryCrossentropy
    else keras$metrics$binary_crossentropy
    do.call(callable, args)
}, py_function_name = "binary_crossentropy")


"man-src/metric_categorical_crossentropy.Rmd" # |>file.edit() # or cmd+click to edit man page
"man-src/metric_categorical_crossentropy/0-upstream.md" # view the upstream doc
#' @eval readLines("man-src/metric_categorical_crossentropy/3-rendered.md")
metric_categorical_crossentropy <-
structure(function (y_true, y_pred, from_logits = FALSE, label_smoothing = 0,
    axis = -1L, ..., name = "categorical_crossentropy", dtype = NULL)
{
    args <- capture_args2(list(label_smoothing = as_integer,
        axis = as_axis))
    callable <- if (missing(y_true) && missing(y_pred))
        keras$metrics$CategoricalCrossentropy
    else keras$metrics$categorical_crossentropy
    do.call(callable, args)
}, py_function_name = "categorical_crossentropy")


"man-src/metric_kl_divergence.Rmd" # |>file.edit() # or cmd+click to edit man page
"man-src/metric_kl_divergence/0-upstream.md" # view the upstream doc
#' @eval readLines("man-src/metric_kl_divergence/3-rendered.md")
metric_kl_divergence <-
structure(function (y_true, y_pred, ..., name = "kl_divergence",
    dtype = NULL)
{
    args <- capture_args2(NULL)
    callable <- if (missing(y_true) && missing(y_pred))
        keras$metrics$KLDivergence
    else keras$metrics$kl_divergence
    do.call(callable, args)
}, py_function_name = "kl_divergence")


"man-src/metric_poisson.Rmd" # |>file.edit() # or cmd+click to edit man page
"man-src/metric_poisson/0-upstream.md" # view the upstream doc
#' @eval readLines("man-src/metric_poisson/3-rendered.md")
metric_poisson <-
structure(function (y_true, y_pred, ..., name = "poisson", dtype = NULL)
{
    args <- capture_args2(NULL)
    callable <- if (missing(y_true) && missing(y_pred))
        keras$metrics$Poisson
    else keras$metrics$poisson
    do.call(callable, args)
}, py_function_name = "poisson")


"man-src/metric_sparse_categorical_crossentropy.Rmd" # |>file.edit() # or cmd+click to edit man page
"man-src/metric_sparse_categorical_crossentropy/0-upstream.md" # view the upstream doc
#' @eval readLines("man-src/metric_sparse_categorical_crossentropy/3-rendered.md")
metric_sparse_categorical_crossentropy <-
structure(function (y_true, y_pred, from_logits = FALSE, ignore_class = NULL,
    axis = -1L, ..., name = "sparse_categorical_crossentropy",
    dtype = NULL)
{
    args <- capture_args2(list(axis = as_axis, ignore_class = as_integer))
    callable <- if (missing(y_true) && missing(y_pred))
        keras$metrics$SparseCategoricalCrossentropy
    else keras$metrics$sparse_categorical_crossentropy
    do.call(callable, args)
}, py_function_name = "sparse_categorical_crossentropy")


"man-src/metric_mean.Rmd" # |>file.edit() # or cmd+click to edit man page
"man-src/metric_mean/0-upstream.md" # view the upstream doc
#' @eval readLines("man-src/metric_mean/3-rendered.md")
metric_mean <-
function (..., name = "mean", dtype = NULL)
{
    args <- capture_args2(NULL)
    do.call(keras$metrics$Mean, args)
}


"man-src/metric_mean_wrapper.Rmd" # |>file.edit() # or cmd+click to edit man page
"man-src/metric_mean_wrapper/0-upstream.md" # view the upstream doc
#' @eval readLines("man-src/metric_mean_wrapper/3-rendered.md")
metric_mean_wrapper <-
function (..., fn, name = NULL, dtype = NULL)
{
    args <- capture_args2(NULL)
    do.call(keras$metrics$MeanMetricWrapper, args)
}


"man-src/metric_sum.Rmd" # |>file.edit() # or cmd+click to edit man page
"man-src/metric_sum/0-upstream.md" # view the upstream doc
#' @eval readLines("man-src/metric_sum/3-rendered.md")
metric_sum <-
function (..., name = "sum", dtype = NULL)
{
    args <- capture_args2(NULL)
    do.call(keras$metrics$Sum, args)
}


"man-src/metric_cosine_similarity.Rmd" # |>file.edit() # or cmd+click to edit man page
"man-src/metric_cosine_similarity/0-upstream.md" # view the upstream doc
#' @eval readLines("man-src/metric_cosine_similarity/3-rendered.md")
metric_cosine_similarity <-
function (..., name = "cosine_similarity", dtype = NULL, axis = -1L)
{
    args <- capture_args2(list(axis = as_axis))
    do.call(keras$metrics$CosineSimilarity, args)
}


"man-src/metric_log_cosh_error.Rmd" # |>file.edit() # or cmd+click to edit man page
"man-src/metric_log_cosh_error/0-upstream.md" # view the upstream doc
#' @eval readLines("man-src/metric_log_cosh_error/3-rendered.md")
metric_log_cosh_error <-
function (..., name = "logcosh", dtype = NULL)
{
    args <- capture_args2(NULL)
    do.call(keras$metrics$LogCoshError, args)
}


"man-src/metric_mean_absolute_error.Rmd" # |>file.edit() # or cmd+click to edit man page
"man-src/metric_mean_absolute_error/0-upstream.md" # view the upstream doc
#' @eval readLines("man-src/metric_mean_absolute_error/3-rendered.md")
metric_mean_absolute_error <-
structure(function (y_true, y_pred, ..., name = "mean_absolute_error",
    dtype = NULL)
{
    args <- capture_args2(NULL)
    callable <- if (missing(y_true) && missing(y_pred))
        keras$metrics$MeanAbsoluteError
    else keras$metrics$mean_absolute_error
    do.call(callable, args)
}, py_function_name = "mean_absolute_error")


"man-src/metric_mean_absolute_percentage_error.Rmd" # |>file.edit() # or cmd+click to edit man page
"man-src/metric_mean_absolute_percentage_error/0-upstream.md" # view the upstream doc
#' @eval readLines("man-src/metric_mean_absolute_percentage_error/3-rendered.md")
metric_mean_absolute_percentage_error <-
structure(function (y_true, y_pred, ..., name = "mean_absolute_percentage_error",
    dtype = NULL)
{
    args <- capture_args2(NULL)
    callable <- if (missing(y_true) && missing(y_pred))
        keras$metrics$MeanAbsolutePercentageError
    else keras$metrics$mean_absolute_percentage_error
    do.call(callable, args)
}, py_function_name = "mean_absolute_percentage_error")


"man-src/metric_mean_squared_error.Rmd" # |>file.edit() # or cmd+click to edit man page
"man-src/metric_mean_squared_error/0-upstream.md" # view the upstream doc
#' @eval readLines("man-src/metric_mean_squared_error/3-rendered.md")
metric_mean_squared_error <-
structure(function (y_true, y_pred, ..., name = "mean_squared_error",
    dtype = NULL)
{
    args <- capture_args2(NULL)
    callable <- if (missing(y_true) && missing(y_pred))
        keras$metrics$MeanSquaredError
    else keras$metrics$mean_squared_error
    do.call(callable, args)
}, py_function_name = "mean_squared_error")


"man-src/metric_mean_squared_logarithmic_error.Rmd" # |>file.edit() # or cmd+click to edit man page
"man-src/metric_mean_squared_logarithmic_error/0-upstream.md" # view the upstream doc
#' @eval readLines("man-src/metric_mean_squared_logarithmic_error/3-rendered.md")
metric_mean_squared_logarithmic_error <-
structure(function (y_true, y_pred, ..., name = "mean_squared_logarithmic_error",
    dtype = NULL)
{
    args <- capture_args2(NULL)
    callable <- if (missing(y_true) && missing(y_pred))
        keras$metrics$MeanSquaredLogarithmicError
    else keras$metrics$mean_squared_logarithmic_error
    do.call(callable, args)
}, py_function_name = "mean_squared_logarithmic_error")


"man-src/metric_r2_score.Rmd" # |>file.edit() # or cmd+click to edit man page
"man-src/metric_r2_score/0-upstream.md" # view the upstream doc
#' @eval readLines("man-src/metric_r2_score/3-rendered.md")
metric_r2_score <-
function (..., class_aggregation = "uniform_average", num_regressors = 0L,
    name = "r2_score", dtype = NULL)
{
    args <- capture_args2(list(num_regressors = as_integer))
    do.call(keras$metrics$R2Score, args)
}


"man-src/metric_root_mean_squared_error.Rmd" # |>file.edit() # or cmd+click to edit man page
"man-src/metric_root_mean_squared_error/0-upstream.md" # view the upstream doc
#' @eval readLines("man-src/metric_root_mean_squared_error/3-rendered.md")
metric_root_mean_squared_error <-
function (..., name = "root_mean_squared_error", dtype = NULL)
{
    args <- capture_args2(NULL)
    do.call(keras$metrics$RootMeanSquaredError, args)
}
