## Autogenerated. Do not modify manually.


"man-src/callback_backup_and_restore/1-formatted.md" # view the upstream doc
"man-src/callback_backup_and_restore/2-translated.Rmd" # |>file.edit() # or cmd+click to edit man page
#' @eval readLines("man-src/callback_backup_and_restore/3-rendered.md")
callback_backup_and_restore <-
function (backup_dir, save_freq = "epoch", delete_checkpoint = TRUE)
{
    args <- capture_args2(list(save_freq = as_integer))
    do.call(keras$callbacks$BackupAndRestore, args)
}


"man-src/callback_csv_logger/1-formatted.md" # view the upstream doc
"man-src/callback_csv_logger/2-translated.Rmd" # |>file.edit() # or cmd+click to edit man page
#' @eval readLines("man-src/callback_csv_logger/3-rendered.md")
callback_csv_logger <-
function (filename, separator = ",", append = FALSE)
{
    args <- capture_args2(NULL)
    do.call(keras$callbacks$CSVLogger, args)
}


"man-src/callback_early_stopping/1-formatted.md" # view the upstream doc
"man-src/callback_early_stopping/2-translated.Rmd" # |>file.edit() # or cmd+click to edit man page
#' @eval readLines("man-src/callback_early_stopping/3-rendered.md")
callback_early_stopping <-
function (monitor = "val_loss", min_delta = 0L, patience = 0L,
    verbose = 0L, mode = "auto", baseline = NULL, restore_best_weights = FALSE,
    start_from_epoch = 0L)
{
    args <- capture_args2(list(min_delta = as_integer, patience = as_integer,
        verbose = as_integer, start_from_epoch = as_integer))
    do.call(keras$callbacks$EarlyStopping, args)
}


"man-src/callback_lambda/1-formatted.md" # view the upstream doc
"man-src/callback_lambda/2-translated.Rmd" # |>file.edit() # or cmd+click to edit man page
#' @eval readLines("man-src/callback_lambda/3-rendered.md")
callback_lambda <-
function (on_epoch_begin = NULL, on_epoch_end = NULL, on_train_begin = NULL,
    on_train_end = NULL, on_train_batch_begin = NULL, on_train_batch_end = NULL,
    ...)
{
    args <- capture_args2(NULL)
    do.call(keras$callbacks$LambdaCallback, args)
}


"man-src/callback_learning_rate_scheduler/1-formatted.md" # view the upstream doc
"man-src/callback_learning_rate_scheduler/2-translated.Rmd" # |>file.edit() # or cmd+click to edit man page
#' @eval readLines("man-src/callback_learning_rate_scheduler/3-rendered.md")
callback_learning_rate_scheduler <-
function (schedule, verbose = 0L)
{
    args <- capture_args2(list(schedule = as_integer, verbose = as_integer))
    do.call(keras$callbacks$LearningRateScheduler, args)
}


"man-src/callback_model_checkpoint/1-formatted.md" # view the upstream doc
"man-src/callback_model_checkpoint/2-translated.Rmd" # |>file.edit() # or cmd+click to edit man page
#' @eval readLines("man-src/callback_model_checkpoint/3-rendered.md")
callback_model_checkpoint <-
function (filepath, monitor = "val_loss", verbose = 0L, save_best_only = FALSE,
    save_weights_only = FALSE, mode = "auto", save_freq = "epoch",
    initial_value_threshold = NULL)
{
    args <- capture_args2(list(verbose = as_integer, save_freq = as_integer))
    do.call(keras$callbacks$ModelCheckpoint, args)
}


"man-src/callback_progbar_logger/1-formatted.md" # view the upstream doc
"man-src/callback_progbar_logger/2-translated.Rmd" # |>file.edit() # or cmd+click to edit man page
#' @eval readLines("man-src/callback_progbar_logger/3-rendered.md")
callback_progbar_logger <-
function (count_mode = NULL)
{
    args <- capture_args2(NULL)
    do.call(keras$callbacks$ProgbarLogger, args)
}


"man-src/callback_reduce_lr_on_plateau/1-formatted.md" # view the upstream doc
"man-src/callback_reduce_lr_on_plateau/2-translated.Rmd" # |>file.edit() # or cmd+click to edit man page
#' @eval readLines("man-src/callback_reduce_lr_on_plateau/3-rendered.md")
callback_reduce_lr_on_plateau <-
function (monitor = "val_loss", factor = 0.1, patience = 10L,
    verbose = 0L, mode = "auto", min_delta = 1e-04, cooldown = 0L,
    min_lr = 0L, ...)
{
    args <- capture_args2(list(patience = as_integer, verbose = as_integer,
        cooldown = as_integer, min_lr = as_integer))
    do.call(keras$callbacks$ReduceLROnPlateau, args)
}


"man-src/callback_remote_monitor/1-formatted.md" # view the upstream doc
"man-src/callback_remote_monitor/2-translated.Rmd" # |>file.edit() # or cmd+click to edit man page
#' @eval readLines("man-src/callback_remote_monitor/3-rendered.md")
callback_remote_monitor <-
function (root = "http://localhost:9000", path = "/publish/epoch/end/",
    field = "data", headers = NULL, send_as_json = FALSE)
{
    args <- capture_args2(NULL)
    do.call(keras$callbacks$RemoteMonitor, args)
}


"man-src/callback_tensorboard/1-formatted.md" # view the upstream doc
"man-src/callback_tensorboard/2-translated.Rmd" # |>file.edit() # or cmd+click to edit man page
#' @eval readLines("man-src/callback_tensorboard/3-rendered.md")
callback_tensorboard <-
function (log_dir = "logs", histogram_freq = 0L, write_graph = TRUE,
    write_images = FALSE, write_steps_per_second = FALSE, update_freq = "epoch",
    profile_batch = 0L, embeddings_freq = 0L, embeddings_metadata = NULL)
{
    args <- capture_args2(list(histogram_freq = as_integer, update_freq = as_integer,
        profile_batch = as_integer, embeddings_freq = as_integer))
    do.call(keras$callbacks$TensorBoard, args)
}


"man-src/callback_terminate_on_nan/1-formatted.md" # view the upstream doc
"man-src/callback_terminate_on_nan/2-translated.Rmd" # |>file.edit() # or cmd+click to edit man page
#' @eval readLines("man-src/callback_terminate_on_nan/3-rendered.md")
callback_terminate_on_nan <-
function ()
{
    args <- capture_args2(NULL)
    do.call(keras$callbacks$TerminateOnNaN, args)
}
