## Autogenerated. Do not modify manually.


#        file.edit("man-src/layer_torch_module_wrapper/2-translated.Rmd")
#' @eval readLines("man-src/layer_torch_module_wrapper/3-rendered.md")
layer_torch_module_wrapper <-
function (object, module, name = NULL, ...)
{
    args <- capture_args2(list(input_shape = normalize_shape,
        batch_size = as_integer, batch_input_shape = normalize_shape),
        ignore = "object")
    create_layer(keras$layers$TorchModuleWrapper, object, args)
}
