## Autogenerated. Do not modify manually.


#' @eval readLines("man-roxygen/loss_binary_crossentropy/roxygen.Rmd")
loss_binary_crossentropy <-
structure(function (y_true, y_pred, from_logits = FALSE, label_smoothing = 0,
    axis = -1L, ..., reduction = "sum_over_batch_size", name = "binary_crossentropy")
{
    args <- capture_args2(list(axis = as_axis))
    callable <- if (missing(y_true) && missing(y_pred))
        keras$losses$BinaryCrossentropy
    else keras$losses$binary_crossentropy
    do.call(callable, args)
}, py_function_name = "binary_crossentropy")


#' @eval readLines("man-roxygen/loss_binary_focal_crossentropy/roxygen.Rmd")
loss_binary_focal_crossentropy <-
structure(function (y_true, y_pred, apply_class_balancing = FALSE,
    alpha = 0.25, gamma = 2, from_logits = FALSE, label_smoothing = 0,
    axis = -1L, ..., reduction = "sum_over_batch_size", name = "binary_focal_crossentropy")
{
    args <- capture_args2(list(axis = as_axis))
    callable <- if (missing(y_true) && missing(y_pred))
        keras$losses$BinaryFocalCrossentropy
    else keras$losses$binary_focal_crossentropy
    do.call(callable, args)
}, py_function_name = "binary_focal_crossentropy")


#' @eval readLines("man-roxygen/loss_categorical_crossentropy/roxygen.Rmd")
loss_categorical_crossentropy <-
structure(function (y_true, y_pred, from_logits = FALSE, label_smoothing = 0,
    axis = -1L, ..., reduction = "sum_over_batch_size", name = "categorical_crossentropy")
{
    args <- capture_args2(list(axis = as_axis))
    callable <- if (missing(y_true) && missing(y_pred))
        keras$losses$CategoricalCrossentropy
    else keras$losses$categorical_crossentropy
    do.call(callable, args)
}, py_function_name = "categorical_crossentropy")


#' @eval readLines("man-roxygen/loss_categorical_focal_crossentropy/roxygen.Rmd")
loss_categorical_focal_crossentropy <-
structure(function (y_true, y_pred, alpha = 0.25, gamma = 2,
    from_logits = FALSE, label_smoothing = 0, axis = -1L, ...,
    reduction = "sum_over_batch_size", name = "categorical_focal_crossentropy")
{
    args <- capture_args2(list(axis = as_axis))
    callable <- if (missing(y_true) && missing(y_pred))
        keras$losses$CategoricalFocalCrossentropy
    else keras$losses$categorical_focal_crossentropy
    do.call(callable, args)
}, py_function_name = "categorical_focal_crossentropy")


#' @eval readLines("man-roxygen/loss_categorical_hinge/roxygen.Rmd")
loss_categorical_hinge <-
structure(function (y_true, y_pred, ..., reduction = "sum_over_batch_size",
    name = "categorical_hinge")
{
    args <- capture_args2(NULL)
    callable <- if (missing(y_true) && missing(y_pred))
        keras$losses$CategoricalHinge
    else keras$losses$categorical_hinge
    do.call(callable, args)
}, py_function_name = "categorical_hinge")


#' @eval readLines("man-roxygen/loss_cosine_similarity/roxygen.Rmd")
loss_cosine_similarity <-
structure(function (y_true, y_pred, axis = -1L, ..., reduction = "sum_over_batch_size",
    name = "cosine_similarity")
{
    args <- capture_args2(list(axis = as_axis))
    callable <- if (missing(y_true) && missing(y_pred))
        keras$losses$CosineSimilarity
    else keras$losses$cosine_similarity
    do.call(callable, args)
}, py_function_name = "cosine_similarity")


#' @eval readLines("man-roxygen/loss_hinge/roxygen.Rmd")
loss_hinge <-
structure(function (y_true, y_pred, ..., reduction = "sum_over_batch_size",
    name = "hinge")
{
    args <- capture_args2(NULL)
    callable <- if (missing(y_true) && missing(y_pred))
        keras$losses$Hinge
    else keras$losses$hinge
    do.call(callable, args)
}, py_function_name = "hinge")


#' @eval readLines("man-roxygen/loss_huber/roxygen.Rmd")
loss_huber <-
structure(function (y_true, y_pred, delta = 1, ..., reduction = "sum_over_batch_size",
    name = "huber_loss")
{
    args <- capture_args2(NULL)
    callable <- if (missing(y_true) && missing(y_pred))
        keras$losses$Huber
    else keras$losses$huber
    do.call(callable, args)
}, py_function_name = "huber")


#' @eval readLines("man-roxygen/loss_kl_divergence/roxygen.Rmd")
loss_kl_divergence <-
structure(function (y_true, y_pred, ..., reduction = "sum_over_batch_size",
    name = "kl_divergence")
{
    args <- capture_args2(NULL)
    callable <- if (missing(y_true) && missing(y_pred))
        keras$losses$KLDivergence
    else keras$losses$kl_divergence
    do.call(callable, args)
}, py_function_name = "kl_divergence")


#' @eval readLines("man-roxygen/loss_log_cosh/roxygen.Rmd")
loss_log_cosh <-
structure(function (y_true, y_pred, ..., reduction = "sum_over_batch_size",
    name = "log_cosh")
{
    args <- capture_args2(NULL)
    callable <- if (missing(y_true) && missing(y_pred))
        keras$losses$LogCosh
    else keras$losses$log_cosh
    do.call(callable, args)
}, py_function_name = "log_cosh")


#' @eval readLines("man-roxygen/loss_mean_absolute_error/roxygen.Rmd")
loss_mean_absolute_error <-
structure(function (y_true, y_pred, ..., reduction = "sum_over_batch_size",
    name = "mean_absolute_error")
{
    args <- capture_args2(NULL)
    callable <- if (missing(y_true) && missing(y_pred))
        keras$losses$MeanAbsoluteError
    else keras$losses$mean_absolute_error
    do.call(callable, args)
}, py_function_name = "mean_absolute_error")


#' @eval readLines("man-roxygen/loss_mean_absolute_percentage_error/roxygen.Rmd")
loss_mean_absolute_percentage_error <-
structure(function (y_true, y_pred, ..., reduction = "sum_over_batch_size",
    name = "mean_absolute_percentage_error")
{
    args <- capture_args2(NULL)
    callable <- if (missing(y_true) && missing(y_pred))
        keras$losses$MeanAbsolutePercentageError
    else keras$losses$mean_absolute_percentage_error
    do.call(callable, args)
}, py_function_name = "mean_absolute_percentage_error")


#' @eval readLines("man-roxygen/loss_mean_squared_error/roxygen.Rmd")
loss_mean_squared_error <-
structure(function (y_true, y_pred, ..., reduction = "sum_over_batch_size",
    name = "mean_squared_error")
{
    args <- capture_args2(NULL)
    callable <- if (missing(y_true) && missing(y_pred))
        keras$losses$MeanSquaredError
    else keras$losses$mean_squared_error
    do.call(callable, args)
}, py_function_name = "mean_squared_error")


#' @eval readLines("man-roxygen/loss_mean_squared_logarithmic_error/roxygen.Rmd")
loss_mean_squared_logarithmic_error <-
structure(function (y_true, y_pred, ..., reduction = "sum_over_batch_size",
    name = "mean_squared_logarithmic_error")
{
    args <- capture_args2(NULL)
    callable <- if (missing(y_true) && missing(y_pred))
        keras$losses$MeanSquaredLogarithmicError
    else keras$losses$mean_squared_logarithmic_error
    do.call(callable, args)
}, py_function_name = "mean_squared_logarithmic_error")


#' @eval readLines("man-roxygen/loss_poisson/roxygen.Rmd")
loss_poisson <-
structure(function (y_true, y_pred, ..., reduction = "sum_over_batch_size",
    name = "poisson")
{
    args <- capture_args2(NULL)
    callable <- if (missing(y_true) && missing(y_pred))
        keras$losses$Poisson
    else keras$losses$poisson
    do.call(callable, args)
}, py_function_name = "poisson")


#' @eval readLines("man-roxygen/loss_sparse_categorical_crossentropy/roxygen.Rmd")
loss_sparse_categorical_crossentropy <-
structure(function (y_true, y_pred, from_logits = FALSE, ignore_class = NULL,
    axis = -1L, ..., reduction = "sum_over_batch_size", name = "sparse_categorical_crossentropy")
{
    args <- capture_args2(list(ignore_class = as_integer, axis = as_axis))
    callable <- if (missing(y_true) && missing(y_pred))
        keras$losses$SparseCategoricalCrossentropy
    else keras$losses$sparse_categorical_crossentropy
    do.call(callable, args)
}, py_function_name = "sparse_categorical_crossentropy")


#' @eval readLines("man-roxygen/loss_squared_hinge/roxygen.Rmd")
loss_squared_hinge <-
structure(function (y_true, y_pred, ..., reduction = "sum_over_batch_size",
    name = "squared_hinge")
{
    args <- capture_args2(NULL)
    callable <- if (missing(y_true) && missing(y_pred))
        keras$losses$SquaredHinge
    else keras$losses$squared_hinge
    do.call(callable, args)
}, py_function_name = "squared_hinge")
