## Autogenerated. Do not modify manually.


# keras$layers$Add
# keras.layers.Add
# keras_core.src.layers.merging.add.Add
r"-(Performs elementwise addition operation.

    It takes as input a list of tensors, all of the same shape,
    and returns a single tensor (also of the same shape).

    Examples:

    >>> input_shape = (2, 3, 4)
    >>> x1 = np.random.rand(*input_shape)
    >>> x2 = np.random.rand(*input_shape)
    >>> y = keras.layers.Add()([x1, x2])

    Usage in a Keras model:

    >>> input1 = keras.layers.Input(shape=(16,))
    >>> x1 = keras.layers.Dense(8, activation='relu')(input1)
    >>> input2 = keras.layers.Input(shape=(32,))
    >>> x2 = keras.layers.Dense(8, activation='relu')(input2)
    >>> # equivalent to `added = keras.layers.add([x1, x2])`
    >>> added = keras.layers.Add()([x1, x2])
    >>> out = keras.layers.Dense(4)(added)
    >>> model = keras.models.Model(inputs=[input1, input2], outputs=out)

    )-"


# keras.src.layers.merging.add.Add
#' Performs elementwise addition operation.
#'
#' @description
#' It takes as input a list of tensors, all of the same shape,
#' and returns a single tensor (also of the same shape).
#'
#' # Examples
#' ```python
#' input_shape = (2, 3, 4)
#' x1 = np.random.rand(*input_shape)
#' x2 = np.random.rand(*input_shape)
#' y = keras.layers.Add()([x1, x2])
#' ```
#'
#' Usage in a Keras model:
#'
#' ```python
#' input1 = keras.layers.Input(shape=(16,))
#' x1 = keras.layers.Dense(8, activation='relu')(input1)
#' input2 = keras.layers.Input(shape=(32,))
#' x2 = keras.layers.Dense(8, activation='relu')(input2)
#' # equivalent to `added = keras.layers.add([x1, x2])`
#' added = keras.layers.Add()([x1, x2])
#' out = keras.layers.Dense(4)(added)
#' model = keras.models.Model(inputs=[input1, input2], outputs=out)
#' ```
#'
#' @param ... Passed on to the Python callable
#' @param inputs layers to combine
#'
#' @export
#' @family merging layers
#' @seealso
#' + <https://www.tensorflow.org/api_docs/python/tf/keras/layers/Add>
layer_add <-
function (inputs, ...)
{
    args <- capture_args2(list(input_shape = normalize_shape,
        batch_size = as_integer, batch_input_shape = normalize_shape),
        ignore = c("...", "inputs"))
    dots <- split_dots_named_unnamed(list(...))
    if (missing(inputs))
        inputs <- NULL
    else if (!is.null(inputs) && !is.list(inputs))
        inputs <- list(inputs)
    inputs <- c(inputs, dots$unnamed)
    args <- c(args, dots$named)
    layer <- do.call(keras$layers$Add, args)
    if (length(inputs))
        layer(inputs)
    else layer
}


# keras$layers$Average
# keras.layers.Average
# keras_core.src.layers.merging.average.Average
r"-(Averages a list of inputs element-wise..

    It takes as input a list of tensors, all of the same shape,
    and returns a single tensor (also of the same shape).

    Examples:

    >>> input_shape = (2, 3, 4)
    >>> x1 = np.random.rand(*input_shape)
    >>> x2 = np.random.rand(*input_shape)
    >>> y = keras.layers.Average()([x1, x2])

    Usage in a Keras model:

    >>> input1 = keras.layers.Input(shape=(16,))
    >>> x1 = keras.layers.Dense(8, activation='relu')(input1)
    >>> input2 = keras.layers.Input(shape=(32,))
    >>> x2 = keras.layers.Dense(8, activation='relu')(input2)
    >>> # equivalent to `y = keras.layers.average([x1, x2])`
    >>> y = keras.layers.Average()([x1, x2])
    >>> out = keras.layers.Dense(4)(y)
    >>> model = keras.models.Model(inputs=[input1, input2], outputs=out)

    )-"


# keras.src.layers.merging.average.Average
#' Averages a list of inputs element-wise..
#'
#' @description
#' It takes as input a list of tensors, all of the same shape,
#' and returns a single tensor (also of the same shape).
#'
#' # Examples
#' ```python
#' input_shape = (2, 3, 4)
#' x1 = np.random.rand(*input_shape)
#' x2 = np.random.rand(*input_shape)
#' y = keras.layers.Average()([x1, x2])
#' ```
#'
#' Usage in a Keras model:
#'
#' ```python
#' input1 = keras.layers.Input(shape=(16,))
#' x1 = keras.layers.Dense(8, activation='relu')(input1)
#' input2 = keras.layers.Input(shape=(32,))
#' x2 = keras.layers.Dense(8, activation='relu')(input2)
#' # equivalent to `y = keras.layers.average([x1, x2])`
#' y = keras.layers.Average()([x1, x2])
#' out = keras.layers.Dense(4)(y)
#' model = keras.models.Model(inputs=[input1, input2], outputs=out)
#' ```
#'
#' @param ... Passed on to the Python callable
#' @param inputs layers to combine
#'
#' @export
#' @family merging layers
#' @seealso
#' + <https://www.tensorflow.org/api_docs/python/tf/keras/layers/Average>
layer_average <-
function (inputs, ...)
{
    args <- capture_args2(list(input_shape = normalize_shape,
        batch_size = as_integer, batch_input_shape = normalize_shape),
        ignore = c("...", "inputs"))
    dots <- split_dots_named_unnamed(list(...))
    if (missing(inputs))
        inputs <- NULL
    else if (!is.null(inputs) && !is.list(inputs))
        inputs <- list(inputs)
    inputs <- c(inputs, dots$unnamed)
    args <- c(args, dots$named)
    layer <- do.call(keras$layers$Average, args)
    if (length(inputs))
        layer(inputs)
    else layer
}


# keras$layers$Concatenate
# keras.layers.Concatenate
# keras_core.src.layers.merging.concatenate.Concatenate
r"-(Concatenates a list of inputs.

    It takes as input a list of tensors, all of the same shape except
    for the concatenation axis, and returns a single tensor that is the
    concatenation of all inputs.

    Examples:

    >>> x = np.arange(20).reshape(2, 2, 5)
    >>> y = np.arange(20, 30).reshape(2, 1, 5)
    >>> keras.layers.Concatenate(axis=1)([x, y])

    Usage in a Keras model:

    >>> x1 = keras.layers.Dense(8)(np.arange(10).reshape(5, 2))
    >>> x2 = keras.layers.Dense(8)(np.arange(10, 20).reshape(5, 2))
    >>> y = keras.layers.Concatenate()([x1, x2])

    Args:
        axis: Axis along which to concatenate.
        **kwargs: Standard layer keyword arguments.

    Returns:
        A tensor, the concatenation of the inputs alongside axis `axis`.
    )-"


# keras.src.layers.merging.concatenate.Concatenate
#' Concatenates a list of inputs.
#'
#' @description
#' It takes as input a list of tensors, all of the same shape except
#' for the concatenation axis, and returns a single tensor that is the
#' concatenation of all inputs.
#'
#' # Examples
#' ```python
#' x = np.arange(20).reshape(2, 2, 5)
#' y = np.arange(20, 30).reshape(2, 1, 5)
#' keras.layers.Concatenate(axis=1)([x, y])
#' ```
#'
#' Usage in a Keras model:
#'
#' ```python
#' x1 = keras.layers.Dense(8)(np.arange(10).reshape(5, 2))
#' x2 = keras.layers.Dense(8)(np.arange(10, 20).reshape(5, 2))
#' y = keras.layers.Concatenate()([x1, x2])
#' ```
#'
#' # Returns
#'     A tensor, the concatenation of the inputs alongside axis `axis`.
#'
#' @param axis Axis along which to concatenate.
#' @param ... Standard layer keyword arguments.
#' @param inputs layers to combine
#'
#' @export
#' @family merging layers
#' @seealso
#' + <https://www.tensorflow.org/api_docs/python/tf/keras/layers/Concatenate>
layer_concatenate <-
function (inputs, ..., axis = -1L)
{
    args <- capture_args2(list(axis = as_integer, input_shape = normalize_shape,
        batch_size = as_integer, batch_input_shape = normalize_shape),
        ignore = c("...", "inputs"))
    dots <- split_dots_named_unnamed(list(...))
    if (missing(inputs))
        inputs <- NULL
    else if (!is.null(inputs) && !is.list(inputs))
        inputs <- list(inputs)
    inputs <- c(inputs, dots$unnamed)
    args <- c(args, dots$named)
    layer <- do.call(keras$layers$Concatenate, args)
    if (length(inputs))
        layer(inputs)
    else layer
}


# keras$layers$Dot
# keras.layers.Dot
# keras_core.src.layers.merging.dot.Dot
r"-(Computes element-wise dot product of two tensors.

    It takes a list of inputs of size 2, and the axes
    corresponding to each input along with the dot product
    is to be performed.

    Let's say `x` and `y` are the two input tensors with shapes
    `(2, 3, 5)` and `(2, 10, 3)`. The batch dimension should be
    of same size for both the inputs, and `axes` should correspond
    to the dimensions that have the same size in the corresponding
    inputs. e.g. with `axes=(1, 2)`, the dot product of `x`, and `y`
    will result in a tensor with shape `(2, 5, 10)`

    Examples:

    >>> x = np.arange(10).reshape(1, 5, 2)
    >>> y = np.arange(10, 20).reshape(1, 2, 5)
    >>> keras.layers.Dot(axes=(1, 2))([x, y])

    Usage in a Keras model:

    >>> x1 = keras.layers.Dense(8)(np.arange(10).reshape(5, 2))
    >>> x2 = keras.layers.Dense(8)(np.arange(10, 20).reshape(5, 2))
    >>> y = keras.layers.Dot(axes=1)([x1, x2])

    Args:
        axes: Integer or tuple of integers, axis or axes along which to
            take the dot product. If a tuple, should be two integers
            corresponding to the desired axis from the first input and the
            desired axis from the second input, respectively. Note that the
            size of the two selected axes must match.
        normalize: Whether to L2-normalize samples along the dot product axis
            before taking the dot product. If set to `True`, then
            the output of the dot product is the cosine proximity
            between the two samples.
        **kwargs: Standard layer keyword arguments.

    Returns:
        A tensor, the dot product of the samples from the inputs.
    )-"


# keras.src.layers.merging.dot.Dot
#' Computes element-wise dot product of two tensors.
#'
#' @description
#' It takes a list of inputs of size 2, and the axes
#' corresponding to each input along with the dot product
#' is to be performed.
#'
#' Let's say `x` and `y` are the two input tensors with shapes
#' `(2, 3, 5)` and `(2, 10, 3)`. The batch dimension should be
#' of same size for both the inputs, and `axes` should correspond
#' to the dimensions that have the same size in the corresponding
#' inputs. e.g. with `axes=(1, 2)`, the dot product of `x`, and `y`
#' will result in a tensor with shape `(2, 5, 10)`
#'
#' # Examples
#' ```python
#' x = np.arange(10).reshape(1, 5, 2)
#' y = np.arange(10, 20).reshape(1, 2, 5)
#' keras.layers.Dot(axes=(1, 2))([x, y])
#' ```
#'
#' Usage in a Keras model:
#'
#' ```python
#' x1 = keras.layers.Dense(8)(np.arange(10).reshape(5, 2))
#' x2 = keras.layers.Dense(8)(np.arange(10, 20).reshape(5, 2))
#' y = keras.layers.Dot(axes=1)([x1, x2])
#' ```
#'
#' # Returns
#'     A tensor, the dot product of the samples from the inputs.
#'
#' @param axes Integer or tuple of integers, axis or axes along which to
#'     take the dot product. If a tuple, should be two integers
#'     corresponding to the desired axis from the first input and the
#'     desired axis from the second input, respectively. Note that the
#'     size of the two selected axes must match.
#' @param normalize Whether to L2-normalize samples along the dot product axis
#'     before taking the dot product. If set to `True`, then
#'     the output of the dot product is the cosine proximity
#'     between the two samples.
#' @param ... Standard layer keyword arguments.
#' @param inputs layers to combine
#'
#' @export
#' @family merging layers
#' @seealso
#' + <https://www.tensorflow.org/api_docs/python/tf/keras/layers/Dot>
layer_dot <-
function (inputs, ..., axes, normalize = FALSE)
{
    args <- capture_args2(list(axes = as_integer, input_shape = normalize_shape,
        batch_size = as_integer, batch_input_shape = normalize_shape),
        ignore = c("...", "inputs"))
    dots <- split_dots_named_unnamed(list(...))
    if (missing(inputs))
        inputs <- NULL
    else if (!is.null(inputs) && !is.list(inputs))
        inputs <- list(inputs)
    inputs <- c(inputs, dots$unnamed)
    args <- c(args, dots$named)
    layer <- do.call(keras$layers$Dot, args)
    if (length(inputs))
        layer(inputs)
    else layer
}


# keras$layers$Maximum
# keras.layers.Maximum
# keras_core.src.layers.merging.maximum.Maximum
r"-(Computes element-wise maximum on a list of inputs.

    It takes as input a list of tensors, all of the same shape,
    and returns a single tensor (also of the same shape).

    Examples:

    >>> input_shape = (2, 3, 4)
    >>> x1 = np.random.rand(*input_shape)
    >>> x2 = np.random.rand(*input_shape)
    >>> y = keras.layers.Maximum()([x1, x2])

    Usage in a Keras model:

    >>> input1 = keras.layers.Input(shape=(16,))
    >>> x1 = keras.layers.Dense(8, activation='relu')(input1)
    >>> input2 = keras.layers.Input(shape=(32,))
    >>> x2 = keras.layers.Dense(8, activation='relu')(input2)
    >>> # equivalent to `y = keras.layers.maximum([x1, x2])`
    >>> y = keras.layers.Maximum()([x1, x2])
    >>> out = keras.layers.Dense(4)(y)
    >>> model = keras.models.Model(inputs=[input1, input2], outputs=out)

    )-"


# keras.src.layers.merging.maximum.Maximum
#' Computes element-wise maximum on a list of inputs.
#'
#' @description
#' It takes as input a list of tensors, all of the same shape,
#' and returns a single tensor (also of the same shape).
#'
#' # Examples
#' ```python
#' input_shape = (2, 3, 4)
#' x1 = np.random.rand(*input_shape)
#' x2 = np.random.rand(*input_shape)
#' y = keras.layers.Maximum()([x1, x2])
#' ```
#'
#' Usage in a Keras model:
#'
#' ```python
#' input1 = keras.layers.Input(shape=(16,))
#' x1 = keras.layers.Dense(8, activation='relu')(input1)
#' input2 = keras.layers.Input(shape=(32,))
#' x2 = keras.layers.Dense(8, activation='relu')(input2)
#' # equivalent to `y = keras.layers.maximum([x1, x2])`
#' y = keras.layers.Maximum()([x1, x2])
#' out = keras.layers.Dense(4)(y)
#' model = keras.models.Model(inputs=[input1, input2], outputs=out)
#' ```
#'
#' @param ... Passed on to the Python callable
#' @param inputs layers to combine
#'
#' @export
#' @family merging layers
#' @seealso
#' + <https://www.tensorflow.org/api_docs/python/tf/keras/layers/Maximum>
layer_maximum <-
function (inputs, ...)
{
    args <- capture_args2(list(input_shape = normalize_shape,
        batch_size = as_integer, batch_input_shape = normalize_shape),
        ignore = c("...", "inputs"))
    dots <- split_dots_named_unnamed(list(...))
    if (missing(inputs))
        inputs <- NULL
    else if (!is.null(inputs) && !is.list(inputs))
        inputs <- list(inputs)
    inputs <- c(inputs, dots$unnamed)
    args <- c(args, dots$named)
    layer <- do.call(keras$layers$Maximum, args)
    if (length(inputs))
        layer(inputs)
    else layer
}


# keras$layers$Minimum
# keras.layers.Minimum
# keras_core.src.layers.merging.minimum.Minimum
r"-(Computes elementwise minimum on a list of inputs.

    It takes as input a list of tensors, all of the same shape,
    and returns a single tensor (also of the same shape).

    Examples:

    >>> input_shape = (2, 3, 4)
    >>> x1 = np.random.rand(*input_shape)
    >>> x2 = np.random.rand(*input_shape)
    >>> y = keras.layers.Minimum()([x1, x2])

    Usage in a Keras model:

    >>> input1 = keras.layers.Input(shape=(16,))
    >>> x1 = keras.layers.Dense(8, activation='relu')(input1)
    >>> input2 = keras.layers.Input(shape=(32,))
    >>> x2 = keras.layers.Dense(8, activation='relu')(input2)
    >>> # equivalent to `y = keras.layers.minimum([x1, x2])`
    >>> y = keras.layers.Minimum()([x1, x2])
    >>> out = keras.layers.Dense(4)(y)
    >>> model = keras.models.Model(inputs=[input1, input2], outputs=out)

    )-"


# keras.src.layers.merging.minimum.Minimum
#' Computes elementwise minimum on a list of inputs.
#'
#' @description
#' It takes as input a list of tensors, all of the same shape,
#' and returns a single tensor (also of the same shape).
#'
#' # Examples
#' ```python
#' input_shape = (2, 3, 4)
#' x1 = np.random.rand(*input_shape)
#' x2 = np.random.rand(*input_shape)
#' y = keras.layers.Minimum()([x1, x2])
#' ```
#'
#' Usage in a Keras model:
#'
#' ```python
#' input1 = keras.layers.Input(shape=(16,))
#' x1 = keras.layers.Dense(8, activation='relu')(input1)
#' input2 = keras.layers.Input(shape=(32,))
#' x2 = keras.layers.Dense(8, activation='relu')(input2)
#' # equivalent to `y = keras.layers.minimum([x1, x2])`
#' y = keras.layers.Minimum()([x1, x2])
#' out = keras.layers.Dense(4)(y)
#' model = keras.models.Model(inputs=[input1, input2], outputs=out)
#' ```
#'
#' @param ... Passed on to the Python callable
#' @param inputs layers to combine
#'
#' @export
#' @family merging layers
#' @seealso
#' + <https://www.tensorflow.org/api_docs/python/tf/keras/layers/Minimum>
layer_minimum <-
function (inputs, ...)
{
    args <- capture_args2(list(input_shape = normalize_shape,
        batch_size = as_integer, batch_input_shape = normalize_shape),
        ignore = c("...", "inputs"))
    dots <- split_dots_named_unnamed(list(...))
    if (missing(inputs))
        inputs <- NULL
    else if (!is.null(inputs) && !is.list(inputs))
        inputs <- list(inputs)
    inputs <- c(inputs, dots$unnamed)
    args <- c(args, dots$named)
    layer <- do.call(keras$layers$Minimum, args)
    if (length(inputs))
        layer(inputs)
    else layer
}


# keras$layers$Multiply
# keras.layers.Multiply
# keras_core.src.layers.merging.multiply.Multiply
r"-(Performs elementwise multiplication.

    It takes as input a list of tensors, all of the same shape,
    and returns a single tensor (also of the same shape).

    Examples:

    >>> input_shape = (2, 3, 4)
    >>> x1 = np.random.rand(*input_shape)
    >>> x2 = np.random.rand(*input_shape)
    >>> y = keras.layers.Multiply()([x1, x2])

    Usage in a Keras model:

    >>> input1 = keras.layers.Input(shape=(16,))
    >>> x1 = keras.layers.Dense(8, activation='relu')(input1)
    >>> input2 = keras.layers.Input(shape=(32,))
    >>> x2 = keras.layers.Dense(8, activation='relu')(input2)
    >>> # equivalent to `y = keras.layers.multiply([x1, x2])`
    >>> y = keras.layers.Multiply()([x1, x2])
    >>> out = keras.layers.Dense(4)(y)
    >>> model = keras.models.Model(inputs=[input1, input2], outputs=out)

    )-"


# keras.src.layers.merging.multiply.Multiply
#' Performs elementwise multiplication.
#'
#' @description
#' It takes as input a list of tensors, all of the same shape,
#' and returns a single tensor (also of the same shape).
#'
#' # Examples
#' ```python
#' input_shape = (2, 3, 4)
#' x1 = np.random.rand(*input_shape)
#' x2 = np.random.rand(*input_shape)
#' y = keras.layers.Multiply()([x1, x2])
#' ```
#'
#' Usage in a Keras model:
#'
#' ```python
#' input1 = keras.layers.Input(shape=(16,))
#' x1 = keras.layers.Dense(8, activation='relu')(input1)
#' input2 = keras.layers.Input(shape=(32,))
#' x2 = keras.layers.Dense(8, activation='relu')(input2)
#' # equivalent to `y = keras.layers.multiply([x1, x2])`
#' y = keras.layers.Multiply()([x1, x2])
#' out = keras.layers.Dense(4)(y)
#' model = keras.models.Model(inputs=[input1, input2], outputs=out)
#' ```
#'
#' @param ... Passed on to the Python callable
#' @param inputs layers to combine
#'
#' @export
#' @family merging layers
#' @seealso
#' + <https://www.tensorflow.org/api_docs/python/tf/keras/layers/Multiply>
layer_multiply <-
function (inputs, ...)
{
    args <- capture_args2(list(input_shape = normalize_shape,
        batch_size = as_integer, batch_input_shape = normalize_shape),
        ignore = c("...", "inputs"))
    dots <- split_dots_named_unnamed(list(...))
    if (missing(inputs))
        inputs <- NULL
    else if (!is.null(inputs) && !is.list(inputs))
        inputs <- list(inputs)
    inputs <- c(inputs, dots$unnamed)
    args <- c(args, dots$named)
    layer <- do.call(keras$layers$Multiply, args)
    if (length(inputs))
        layer(inputs)
    else layer
}


# keras$layers$Subtract
# keras.layers.Subtract
# keras_core.src.layers.merging.subtract.Subtract
r"-(Performs elementwise subtraction.

    It takes as input a list of tensors of size 2 both of the
    same shape, and returns a single tensor (inputs[0] - inputs[1])
    of same shape.

    Examples:

    >>> input_shape = (2, 3, 4)
    >>> x1 = np.random.rand(*input_shape)
    >>> x2 = np.random.rand(*input_shape)
    >>> y = keras.layers.Subtract()([x1, x2])

    Usage in a Keras model:

    >>> input1 = keras.layers.Input(shape=(16,))
    >>> x1 = keras.layers.Dense(8, activation='relu')(input1)
    >>> input2 = keras.layers.Input(shape=(32,))
    >>> x2 = keras.layers.Dense(8, activation='relu')(input2)
    >>> # equivalent to `subtracted = keras.layers.subtract([x1, x2])`
    >>> subtracted = keras.layers.Subtract()([x1, x2])
    >>> out = keras.layers.Dense(4)(subtracted)
    >>> model = keras.models.Model(inputs=[input1, input2], outputs=out)

    )-"


# keras.src.layers.merging.subtract.Subtract
#' Performs elementwise subtraction.
#'
#' @description
#' It takes as input a list of tensors of size 2 both of the
#' same shape, and returns a single tensor `(inputs[0] - inputs[1])`
#' of same shape.
#'
#' # Examples
#' ```python
#' input_shape = (2, 3, 4)
#' x1 = np.random.rand(*input_shape)
#' x2 = np.random.rand(*input_shape)
#' y = keras.layers.Subtract()([x1, x2])
#' ```
#'
#' Usage in a Keras model:
#'
#' ```python
#' input1 = keras.layers.Input(shape=(16,))
#' x1 = keras.layers.Dense(8, activation='relu')(input1)
#' input2 = keras.layers.Input(shape=(32,))
#' x2 = keras.layers.Dense(8, activation='relu')(input2)
#' # equivalent to `subtracted = keras.layers.subtract([x1, x2])`
#' subtracted = keras.layers.Subtract()([x1, x2])
#' out = keras.layers.Dense(4)(subtracted)
#' model = keras.models.Model(inputs=[input1, input2], outputs=out)
#' ```
#'
#' @param ... Passed on to the Python callable
#' @param inputs layers to combine
#'
#' @export
#' @family merging layers
#' @seealso
#' + <https://www.tensorflow.org/api_docs/python/tf/keras/layers/Subtract>
layer_subtract <-
function (inputs, ...)
{
    args <- capture_args2(list(input_shape = normalize_shape,
        batch_size = as_integer, batch_input_shape = normalize_shape),
        ignore = c("...", "inputs"))
    dots <- split_dots_named_unnamed(list(...))
    if (missing(inputs))
        inputs <- NULL
    else if (!is.null(inputs) && !is.list(inputs))
        inputs <- list(inputs)
    inputs <- c(inputs, dots$unnamed)
    args <- c(args, dots$named)
    layer <- do.call(keras$layers$Subtract, args)
    if (length(inputs))
        layer(inputs)
    else layer
}
