## Autogenerated. Do not modify manually.


#' @eval readLines("man-src/layer_add/3-rendered.md")
layer_add <-
function (inputs, ...)
{
    args <- capture_args2(list(input_shape = normalize_shape,
        batch_size = as_integer, batch_input_shape = normalize_shape),
        ignore = c("...", "inputs"))
    dots <- split_dots_named_unnamed(list(...))
    if (missing(inputs))
        inputs <- NULL
    else if (!is.null(inputs) && !is.list(inputs))
        inputs <- list(inputs)
    inputs <- c(inputs, dots$unnamed)
    args <- c(args, dots$named)
    layer <- do.call(keras$layers$Add, args)
    if (length(inputs))
        layer(inputs)
    else layer
}


#' @eval readLines("man-src/layer_average/3-rendered.md")
layer_average <-
function (inputs, ...)
{
    args <- capture_args2(list(input_shape = normalize_shape,
        batch_size = as_integer, batch_input_shape = normalize_shape),
        ignore = c("...", "inputs"))
    dots <- split_dots_named_unnamed(list(...))
    if (missing(inputs))
        inputs <- NULL
    else if (!is.null(inputs) && !is.list(inputs))
        inputs <- list(inputs)
    inputs <- c(inputs, dots$unnamed)
    args <- c(args, dots$named)
    layer <- do.call(keras$layers$Average, args)
    if (length(inputs))
        layer(inputs)
    else layer
}


#' @eval readLines("man-src/layer_concatenate/3-rendered.md")
layer_concatenate <-
function (inputs, ..., axis = -1L)
{
    args <- capture_args2(list(axis = as_integer, input_shape = normalize_shape,
        batch_size = as_integer, batch_input_shape = normalize_shape),
        ignore = c("...", "inputs"))
    dots <- split_dots_named_unnamed(list(...))
    if (missing(inputs))
        inputs <- NULL
    else if (!is.null(inputs) && !is.list(inputs))
        inputs <- list(inputs)
    inputs <- c(inputs, dots$unnamed)
    args <- c(args, dots$named)
    layer <- do.call(keras$layers$Concatenate, args)
    if (length(inputs))
        layer(inputs)
    else layer
}


#' @eval readLines("man-src/layer_dot/3-rendered.md")
layer_dot <-
function (inputs, ..., axes, normalize = FALSE)
{
    args <- capture_args2(list(axes = as_integer, input_shape = normalize_shape,
        batch_size = as_integer, batch_input_shape = normalize_shape),
        ignore = c("...", "inputs"))
    dots <- split_dots_named_unnamed(list(...))
    if (missing(inputs))
        inputs <- NULL
    else if (!is.null(inputs) && !is.list(inputs))
        inputs <- list(inputs)
    inputs <- c(inputs, dots$unnamed)
    args <- c(args, dots$named)
    layer <- do.call(keras$layers$Dot, args)
    if (length(inputs))
        layer(inputs)
    else layer
}


#' @eval readLines("man-src/layer_maximum/3-rendered.md")
layer_maximum <-
function (inputs, ...)
{
    args <- capture_args2(list(input_shape = normalize_shape,
        batch_size = as_integer, batch_input_shape = normalize_shape),
        ignore = c("...", "inputs"))
    dots <- split_dots_named_unnamed(list(...))
    if (missing(inputs))
        inputs <- NULL
    else if (!is.null(inputs) && !is.list(inputs))
        inputs <- list(inputs)
    inputs <- c(inputs, dots$unnamed)
    args <- c(args, dots$named)
    layer <- do.call(keras$layers$Maximum, args)
    if (length(inputs))
        layer(inputs)
    else layer
}


#' @eval readLines("man-src/layer_minimum/3-rendered.md")
layer_minimum <-
function (inputs, ...)
{
    args <- capture_args2(list(input_shape = normalize_shape,
        batch_size = as_integer, batch_input_shape = normalize_shape),
        ignore = c("...", "inputs"))
    dots <- split_dots_named_unnamed(list(...))
    if (missing(inputs))
        inputs <- NULL
    else if (!is.null(inputs) && !is.list(inputs))
        inputs <- list(inputs)
    inputs <- c(inputs, dots$unnamed)
    args <- c(args, dots$named)
    layer <- do.call(keras$layers$Minimum, args)
    if (length(inputs))
        layer(inputs)
    else layer
}


#' @eval readLines("man-src/layer_multiply/3-rendered.md")
layer_multiply <-
function (inputs, ...)
{
    args <- capture_args2(list(input_shape = normalize_shape,
        batch_size = as_integer, batch_input_shape = normalize_shape),
        ignore = c("...", "inputs"))
    dots <- split_dots_named_unnamed(list(...))
    if (missing(inputs))
        inputs <- NULL
    else if (!is.null(inputs) && !is.list(inputs))
        inputs <- list(inputs)
    inputs <- c(inputs, dots$unnamed)
    args <- c(args, dots$named)
    layer <- do.call(keras$layers$Multiply, args)
    if (length(inputs))
        layer(inputs)
    else layer
}


#' @eval readLines("man-src/layer_subtract/3-rendered.md")
layer_subtract <-
function (inputs, ...)
{
    args <- capture_args2(list(input_shape = normalize_shape,
        batch_size = as_integer, batch_input_shape = normalize_shape),
        ignore = c("...", "inputs"))
    dots <- split_dots_named_unnamed(list(...))
    if (missing(inputs))
        inputs <- NULL
    else if (!is.null(inputs) && !is.list(inputs))
        inputs <- list(inputs)
    inputs <- c(inputs, dots$unnamed)
    args <- c(args, dots$named)
    layer <- do.call(keras$layers$Subtract, args)
    if (length(inputs))
        layer(inputs)
    else layer
}
