## Autogenerated. Do not modify manually.


"man-src/optimizer_adadelta/2-translated.Rmd" # |>file.edit() # or cmd+click to edit man page
#' @eval readLines("man-src/optimizer_adadelta/3-rendered.md")
optimizer_adadelta <-
function (learning_rate = 0.001, rho = 0.95, epsilon = 1e-07,
    weight_decay = NULL, clipnorm = NULL, clipvalue = NULL, global_clipnorm = NULL,
    use_ema = FALSE, ema_momentum = 0.99, ema_overwrite_frequency = NULL,
    name = "adadelta", ..., loss_scale_factor = NULL)
{
    args <- capture_args2(list(ema_overwrite_frequency = as_integer))
    do.call(keras$optimizers$Adadelta, args)
}


"man-src/optimizer_adafactor/2-translated.Rmd" # |>file.edit() # or cmd+click to edit man page
#' @eval readLines("man-src/optimizer_adafactor/3-rendered.md")
optimizer_adafactor <-
function (learning_rate = 0.001, beta_2_decay = -0.8, epsilon_1 = 1e-30,
    epsilon_2 = 0.001, clip_threshold = 1, relative_step = TRUE,
    weight_decay = NULL, clipnorm = NULL, clipvalue = NULL, global_clipnorm = NULL,
    use_ema = FALSE, ema_momentum = 0.99, ema_overwrite_frequency = NULL,
    name = "adafactor", ..., loss_scale_factor = NULL)
{
    args <- capture_args2(list(ema_overwrite_frequency = as_integer))
    do.call(keras$optimizers$Adafactor, args)
}


"man-src/optimizer_adagrad/2-translated.Rmd" # |>file.edit() # or cmd+click to edit man page
#' @eval readLines("man-src/optimizer_adagrad/3-rendered.md")
optimizer_adagrad <-
function (learning_rate = 0.001, initial_accumulator_value = 0.1,
    epsilon = 1e-07, weight_decay = NULL, clipnorm = NULL, clipvalue = NULL,
    global_clipnorm = NULL, use_ema = FALSE, ema_momentum = 0.99,
    ema_overwrite_frequency = NULL, name = "adagrad", ..., loss_scale_factor = NULL)
{
    args <- capture_args2(list(ema_overwrite_frequency = as_integer))
    do.call(keras$optimizers$Adagrad, args)
}


"man-src/optimizer_adam/2-translated.Rmd" # |>file.edit() # or cmd+click to edit man page
#' @eval readLines("man-src/optimizer_adam/3-rendered.md")
optimizer_adam <-
function (learning_rate = 0.001, beta_1 = 0.9, beta_2 = 0.999,
    epsilon = 1e-07, amsgrad = FALSE, weight_decay = NULL, clipnorm = NULL,
    clipvalue = NULL, global_clipnorm = NULL, use_ema = FALSE,
    ema_momentum = 0.99, ema_overwrite_frequency = NULL, name = "adam",
    ..., loss_scale_factor = NULL)
{
    args <- capture_args2(list(ema_overwrite_frequency = as_integer))
    do.call(keras$optimizers$Adam, args)
}


"man-src/optimizer_adamax/2-translated.Rmd" # |>file.edit() # or cmd+click to edit man page
#' @eval readLines("man-src/optimizer_adamax/3-rendered.md")
optimizer_adamax <-
function (learning_rate = 0.001, beta_1 = 0.9, beta_2 = 0.999,
    epsilon = 1e-07, weight_decay = NULL, clipnorm = NULL, clipvalue = NULL,
    global_clipnorm = NULL, use_ema = FALSE, ema_momentum = 0.99,
    ema_overwrite_frequency = NULL, name = "adamax", ..., loss_scale_factor = NULL)
{
    args <- capture_args2(list(ema_overwrite_frequency = as_integer))
    do.call(keras$optimizers$Adamax, args)
}


"man-src/optimizer_adam_w/2-translated.Rmd" # |>file.edit() # or cmd+click to edit man page
#' @eval readLines("man-src/optimizer_adam_w/3-rendered.md")
optimizer_adam_w <-
function (learning_rate = 0.001, weight_decay = 0.004, beta_1 = 0.9,
    beta_2 = 0.999, epsilon = 1e-07, amsgrad = FALSE, clipnorm = NULL,
    clipvalue = NULL, global_clipnorm = NULL, use_ema = FALSE,
    ema_momentum = 0.99, ema_overwrite_frequency = NULL, name = "adamw",
    ..., loss_scale_factor = NULL)
{
    args <- capture_args2(list(ema_overwrite_frequency = as_integer))
    do.call(keras$optimizers$AdamW, args)
}


"man-src/optimizer_ftrl/2-translated.Rmd" # |>file.edit() # or cmd+click to edit man page
#' @eval readLines("man-src/optimizer_ftrl/3-rendered.md")
optimizer_ftrl <-
function (learning_rate = 0.001, learning_rate_power = -0.5,
    initial_accumulator_value = 0.1, l1_regularization_strength = 0,
    l2_regularization_strength = 0, l2_shrinkage_regularization_strength = 0,
    beta = 0, weight_decay = NULL, clipnorm = NULL, clipvalue = NULL,
    global_clipnorm = NULL, use_ema = FALSE, ema_momentum = 0.99,
    ema_overwrite_frequency = NULL, name = "ftrl", ..., loss_scale_factor = NULL)
{
    args <- capture_args2(list(ema_overwrite_frequency = as_integer))
    do.call(keras$optimizers$Ftrl, args)
}


"man-src/optimizer_lion/2-translated.Rmd" # |>file.edit() # or cmd+click to edit man page
#' @eval readLines("man-src/optimizer_lion/3-rendered.md")
optimizer_lion <-
function (learning_rate = 0.001, beta_1 = 0.9, beta_2 = 0.99,
    weight_decay = NULL, clipnorm = NULL, clipvalue = NULL, global_clipnorm = NULL,
    use_ema = FALSE, ema_momentum = 0.99, ema_overwrite_frequency = NULL,
    name = "lion", ..., loss_scale_factor = NULL)
{
    args <- capture_args2(list(ema_overwrite_frequency = as_integer))
    do.call(keras$optimizers$Lion, args)
}


"man-src/optimizer_loss_scale/2-translated.Rmd" # |>file.edit() # or cmd+click to edit man page
#' @eval readLines("man-src/optimizer_loss_scale/3-rendered.md")
optimizer_loss_scale <-
function (inner_optimizer, initial_scale = 32768, dynamic_growth_steps = 2000L,
    ..., name = NULL, weight_decay = NULL, clipnorm = NULL, clipvalue = NULL,
    global_clipnorm = NULL, use_ema = NULL, ema_momentum = NULL,
    ema_overwrite_frequency = NULL, loss_scale_factor = NULL)
{
    args <- capture_args2(list(dynamic_growth_steps = as_integer,
        ema_overwrite_frequency = as_integer))
    do.call(keras$optimizers$LossScaleOptimizer, args)
}


"man-src/optimizer_nadam/2-translated.Rmd" # |>file.edit() # or cmd+click to edit man page
#' @eval readLines("man-src/optimizer_nadam/3-rendered.md")
optimizer_nadam <-
function (learning_rate = 0.001, beta_1 = 0.9, beta_2 = 0.999,
    epsilon = 1e-07, weight_decay = NULL, clipnorm = NULL, clipvalue = NULL,
    global_clipnorm = NULL, use_ema = FALSE, ema_momentum = 0.99,
    ema_overwrite_frequency = NULL, name = "nadam", ..., loss_scale_factor = NULL)
{
    args <- capture_args2(list(ema_overwrite_frequency = as_integer))
    do.call(keras$optimizers$Nadam, args)
}


"man-src/optimizer_rmsprop/2-translated.Rmd" # |>file.edit() # or cmd+click to edit man page
#' @eval readLines("man-src/optimizer_rmsprop/3-rendered.md")
optimizer_rmsprop <-
function (learning_rate = 0.001, rho = 0.9, momentum = 0, epsilon = 1e-07,
    centered = FALSE, weight_decay = NULL, clipnorm = NULL, clipvalue = NULL,
    global_clipnorm = NULL, use_ema = FALSE, ema_momentum = 0.99,
    ema_overwrite_frequency = 100L, name = "rmsprop", ..., loss_scale_factor = NULL)
{
    args <- capture_args2(list(ema_overwrite_frequency = as_integer))
    do.call(keras$optimizers$RMSprop, args)
}


"man-src/optimizer_sgd/2-translated.Rmd" # |>file.edit() # or cmd+click to edit man page
#' @eval readLines("man-src/optimizer_sgd/3-rendered.md")
optimizer_sgd <-
function (learning_rate = 0.01, momentum = 0, nesterov = FALSE,
    weight_decay = NULL, clipnorm = NULL, clipvalue = NULL, global_clipnorm = NULL,
    use_ema = FALSE, ema_momentum = 0.99, ema_overwrite_frequency = NULL,
    name = "SGD", ..., loss_scale_factor = NULL)
{
    args <- capture_args2(list(ema_overwrite_frequency = as_integer))
    do.call(keras$optimizers$SGD, args)
}
