## Autogenerated. Do not modify manually.


#' @eval readLines("man-roxygen/constraint_maxnorm/roxygen.Rmd")
constraint_maxnorm <-
function (max_value = 2L, axis = 0L)
{
    args <- capture_args2(list(max_value = as_integer, axis = as_axis))
    do.call(keras$constraints$MaxNorm, args)
}


#' @eval readLines("man-roxygen/constraint_minmaxnorm/roxygen.Rmd")
constraint_minmaxnorm <-
function (min_value = 0, max_value = 1, rate = 1, axis = 0L)
{
    args <- capture_args2(list(axis = as_axis))
    do.call(keras$constraints$MinMaxNorm, args)
}


#' @eval readLines("man-roxygen/constraint_nonneg/roxygen.Rmd")
constraint_nonneg <-
function ()
{
    args <- capture_args2(NULL)
    do.call(keras$constraints$NonNeg, args)
}


#' @eval readLines("man-roxygen/constraint_unitnorm/roxygen.Rmd")
constraint_unitnorm <-
function (axis = 0L)
{
    args <- capture_args2(list(axis = as_axis))
    do.call(keras$constraints$UnitNorm, args)
}
