## Autogenerated. Do not modify manually.


"man-src/layer_activation/2-translated.Rmd" # |>file.edit() # or cmd+click to edit man page
#' @eval readLines("man-src/layer_activation/3-rendered.md")
layer_activation <-
function (object, activation, ...)
{
    args <- capture_args2(list(input_shape = normalize_shape,
        batch_size = as_integer, batch_input_shape = normalize_shape),
        ignore = "object")
    create_layer(keras$layers$Activation, object, args)
}


"man-src/layer_activation_elu/2-translated.Rmd" # |>file.edit() # or cmd+click to edit man page
#' @eval readLines("man-src/layer_activation_elu/3-rendered.md")
layer_activation_elu <-
function (object, alpha = 1, ...)
{
    args <- capture_args2(list(input_shape = normalize_shape,
        batch_size = as_integer, batch_input_shape = normalize_shape),
        ignore = "object")
    create_layer(keras$layers$ELU, object, args)
}


"man-src/layer_activation_leaky_relu/2-translated.Rmd" # |>file.edit() # or cmd+click to edit man page
#' @eval readLines("man-src/layer_activation_leaky_relu/3-rendered.md")
layer_activation_leaky_relu <-
function (object, negative_slope = 0.3, ...)
{
    args <- capture_args2(list(input_shape = normalize_shape,
        batch_size = as_integer, batch_input_shape = normalize_shape),
        ignore = "object")
    create_layer(keras$layers$LeakyReLU, object, args)
}


"man-src/layer_activation_parametric_relu/2-translated.Rmd" # |>file.edit() # or cmd+click to edit man page
#' @eval readLines("man-src/layer_activation_parametric_relu/3-rendered.md")
layer_activation_parametric_relu <-
function (object, alpha_initializer = "Zeros", alpha_regularizer = NULL,
    alpha_constraint = NULL, shared_axes = NULL, ...)
{
    args <- capture_args2(list(input_shape = normalize_shape,
        batch_size = as_integer, batch_input_shape = normalize_shape,
        shared_axes = function (x)
        lapply(x, as_integer)), ignore = "object")
    create_layer(keras$layers$PReLU, object, args)
}


"man-src/layer_activation_relu/2-translated.Rmd" # |>file.edit() # or cmd+click to edit man page
#' @eval readLines("man-src/layer_activation_relu/3-rendered.md")
layer_activation_relu <-
function (object, max_value = NULL, negative_slope = 0, threshold = 0,
    ...)
{
    args <- capture_args2(list(input_shape = normalize_shape,
        batch_size = as_integer, batch_input_shape = normalize_shape),
        ignore = "object")
    create_layer(keras$layers$ReLU, object, args)
}


"man-src/layer_activation_softmax/2-translated.Rmd" # |>file.edit() # or cmd+click to edit man page
#' @eval readLines("man-src/layer_activation_softmax/3-rendered.md")
layer_activation_softmax <-
function (object, axis = -1L, ...)
{
    args <- capture_args2(list(axis = as_integer, input_shape = normalize_shape,
        batch_size = as_integer, batch_input_shape = normalize_shape),
        ignore = "object")
    create_layer(keras$layers$Softmax, object, args)
}
