## Autogenerated. Do not modify manually.


"man-src/image_smart_resize/1-formatted.md" # view the upstream doc
"man-src/image_smart_resize/2-translated.Rmd" # |>file.edit() # or cmd+click to edit man page
#' @eval readLines("man-src/image_smart_resize/3-rendered.md")
image_smart_resize <-
function (x, size, interpolation = "bilinear", data_format = "channels_last",
    backend_module = NULL)
{
    args <- capture_args2(list(size = as_integer))
    do.call(keras$preprocessing$image$smart_resize, args)
}
