## Autogenerated. Do not modify manually.


"man-src/loss_binary_crossentropy.Rmd" # |>file.edit() # or cmd+click to edit man page
"man-src/loss_binary_crossentropy/0-upstream.md" # view the upstream doc
#' @eval readLines("man-src/loss_binary_crossentropy/3-rendered.md")
loss_binary_crossentropy <-
structure(function (y_true, y_pred, from_logits = FALSE, label_smoothing = 0,
    axis = -1L, ..., reduction = "sum_over_batch_size", name = "binary_crossentropy")
{
    args <- capture_args2(list(axis = as_axis, y_true = function (x)
    if (inherits(x, "python.builtin.object"))
        x
    else np_array(x), y_pred = function (x)
    if (inherits(x, "python.builtin.object"))
        x
    else np_array(x)))
    callable <- if (missing(y_true) && missing(y_pred))
        keras$losses$BinaryCrossentropy
    else keras$losses$binary_crossentropy
    do.call(callable, args)
}, py_function_name = "binary_crossentropy")


"man-src/loss_binary_focal_crossentropy.Rmd" # |>file.edit() # or cmd+click to edit man page
"man-src/loss_binary_focal_crossentropy/0-upstream.md" # view the upstream doc
#' @eval readLines("man-src/loss_binary_focal_crossentropy/3-rendered.md")
loss_binary_focal_crossentropy <-
structure(function (y_true, y_pred, apply_class_balancing = FALSE,
    alpha = 0.25, gamma = 2, from_logits = FALSE, label_smoothing = 0,
    axis = -1L, ..., reduction = "sum_over_batch_size", name = "binary_focal_crossentropy")
{
    args <- capture_args2(list(axis = as_axis, y_true = function (x)
    if (inherits(x, "python.builtin.object"))
        x
    else np_array(x), y_pred = function (x)
    if (inherits(x, "python.builtin.object"))
        x
    else np_array(x)))
    callable <- if (missing(y_true) && missing(y_pred))
        keras$losses$BinaryFocalCrossentropy
    else keras$losses$binary_focal_crossentropy
    do.call(callable, args)
}, py_function_name = "binary_focal_crossentropy")


"man-src/loss_categorical_crossentropy.Rmd" # |>file.edit() # or cmd+click to edit man page
"man-src/loss_categorical_crossentropy/0-upstream.md" # view the upstream doc
#' @eval readLines("man-src/loss_categorical_crossentropy/3-rendered.md")
loss_categorical_crossentropy <-
structure(function (y_true, y_pred, from_logits = FALSE, label_smoothing = 0,
    axis = -1L, ..., reduction = "sum_over_batch_size", name = "categorical_crossentropy")
{
    args <- capture_args2(list(axis = as_axis, y_true = function (x)
    if (inherits(x, "python.builtin.object"))
        x
    else np_array(x), y_pred = function (x)
    if (inherits(x, "python.builtin.object"))
        x
    else np_array(x)))
    callable <- if (missing(y_true) && missing(y_pred))
        keras$losses$CategoricalCrossentropy
    else keras$losses$categorical_crossentropy
    do.call(callable, args)
}, py_function_name = "categorical_crossentropy")


"man-src/loss_categorical_focal_crossentropy.Rmd" # |>file.edit() # or cmd+click to edit man page
"man-src/loss_categorical_focal_crossentropy/0-upstream.md" # view the upstream doc
#' @eval readLines("man-src/loss_categorical_focal_crossentropy/3-rendered.md")
loss_categorical_focal_crossentropy <-
structure(function (y_true, y_pred, alpha = 0.25, gamma = 2,
    from_logits = FALSE, label_smoothing = 0, axis = -1L, ...,
    reduction = "sum_over_batch_size", name = "categorical_focal_crossentropy")
{
    args <- capture_args2(list(axis = as_axis, y_true = function (x)
    if (inherits(x, "python.builtin.object"))
        x
    else np_array(x), y_pred = function (x)
    if (inherits(x, "python.builtin.object"))
        x
    else np_array(x)))
    callable <- if (missing(y_true) && missing(y_pred))
        keras$losses$CategoricalFocalCrossentropy
    else keras$losses$categorical_focal_crossentropy
    do.call(callable, args)
}, py_function_name = "categorical_focal_crossentropy")


"man-src/loss_categorical_hinge.Rmd" # |>file.edit() # or cmd+click to edit man page
"man-src/loss_categorical_hinge/0-upstream.md" # view the upstream doc
#' @eval readLines("man-src/loss_categorical_hinge/3-rendered.md")
loss_categorical_hinge <-
structure(function (y_true, y_pred, ..., reduction = "sum_over_batch_size",
    name = "categorical_hinge")
{
    args <- capture_args2(list(y_true = function (x)
    if (inherits(x, "python.builtin.object"))
        x
    else np_array(x), y_pred = function (x)
    if (inherits(x, "python.builtin.object"))
        x
    else np_array(x)))
    callable <- if (missing(y_true) && missing(y_pred))
        keras$losses$CategoricalHinge
    else keras$losses$categorical_hinge
    do.call(callable, args)
}, py_function_name = "categorical_hinge")


"man-src/loss_cosine_similarity.Rmd" # |>file.edit() # or cmd+click to edit man page
"man-src/loss_cosine_similarity/0-upstream.md" # view the upstream doc
#' @eval readLines("man-src/loss_cosine_similarity/3-rendered.md")
loss_cosine_similarity <-
structure(function (y_true, y_pred, axis = -1L, ..., reduction = "sum_over_batch_size",
    name = "cosine_similarity")
{
    args <- capture_args2(list(axis = as_axis, y_true = function (x)
    if (inherits(x, "python.builtin.object"))
        x
    else np_array(x), y_pred = function (x)
    if (inherits(x, "python.builtin.object"))
        x
    else np_array(x)))
    callable <- if (missing(y_true) && missing(y_pred))
        keras$losses$CosineSimilarity
    else keras$losses$cosine_similarity
    do.call(callable, args)
}, py_function_name = "cosine_similarity")


"man-src/loss_hinge.Rmd" # |>file.edit() # or cmd+click to edit man page
"man-src/loss_hinge/0-upstream.md" # view the upstream doc
#' @eval readLines("man-src/loss_hinge/3-rendered.md")
loss_hinge <-
structure(function (y_true, y_pred, ..., reduction = "sum_over_batch_size",
    name = "hinge")
{
    args <- capture_args2(list(y_true = function (x)
    if (inherits(x, "python.builtin.object"))
        x
    else np_array(x), y_pred = function (x)
    if (inherits(x, "python.builtin.object"))
        x
    else np_array(x)))
    callable <- if (missing(y_true) && missing(y_pred))
        keras$losses$Hinge
    else keras$losses$hinge
    do.call(callable, args)
}, py_function_name = "hinge")


"man-src/loss_huber.Rmd" # |>file.edit() # or cmd+click to edit man page
"man-src/loss_huber/0-upstream.md" # view the upstream doc
#' @eval readLines("man-src/loss_huber/3-rendered.md")
loss_huber <-
structure(function (y_true, y_pred, delta = 1, ..., reduction = "sum_over_batch_size",
    name = "huber_loss")
{
    args <- capture_args2(list(y_true = function (x)
    if (inherits(x, "python.builtin.object"))
        x
    else np_array(x), y_pred = function (x)
    if (inherits(x, "python.builtin.object"))
        x
    else np_array(x)))
    callable <- if (missing(y_true) && missing(y_pred))
        keras$losses$Huber
    else keras$losses$huber
    do.call(callable, args)
}, py_function_name = "huber")


"man-src/loss_kl_divergence.Rmd" # |>file.edit() # or cmd+click to edit man page
"man-src/loss_kl_divergence/0-upstream.md" # view the upstream doc
#' @eval readLines("man-src/loss_kl_divergence/3-rendered.md")
loss_kl_divergence <-
structure(function (y_true, y_pred, ..., reduction = "sum_over_batch_size",
    name = "kl_divergence")
{
    args <- capture_args2(list(y_true = function (x)
    if (inherits(x, "python.builtin.object"))
        x
    else np_array(x), y_pred = function (x)
    if (inherits(x, "python.builtin.object"))
        x
    else np_array(x)))
    callable <- if (missing(y_true) && missing(y_pred))
        keras$losses$KLDivergence
    else keras$losses$kl_divergence
    do.call(callable, args)
}, py_function_name = "kl_divergence")


"man-src/loss_log_cosh.Rmd" # |>file.edit() # or cmd+click to edit man page
"man-src/loss_log_cosh/0-upstream.md" # view the upstream doc
#' @eval readLines("man-src/loss_log_cosh/3-rendered.md")
loss_log_cosh <-
structure(function (y_true, y_pred, ..., reduction = "sum_over_batch_size",
    name = "log_cosh")
{
    args <- capture_args2(list(y_true = function (x)
    if (inherits(x, "python.builtin.object"))
        x
    else np_array(x), y_pred = function (x)
    if (inherits(x, "python.builtin.object"))
        x
    else np_array(x)))
    callable <- if (missing(y_true) && missing(y_pred))
        keras$losses$LogCosh
    else keras$losses$log_cosh
    do.call(callable, args)
}, py_function_name = "log_cosh")


"man-src/loss_mean_absolute_error.Rmd" # |>file.edit() # or cmd+click to edit man page
"man-src/loss_mean_absolute_error/0-upstream.md" # view the upstream doc
#' @eval readLines("man-src/loss_mean_absolute_error/3-rendered.md")
loss_mean_absolute_error <-
structure(function (y_true, y_pred, ..., reduction = "sum_over_batch_size",
    name = "mean_absolute_error")
{
    args <- capture_args2(list(y_true = function (x)
    if (inherits(x, "python.builtin.object"))
        x
    else np_array(x), y_pred = function (x)
    if (inherits(x, "python.builtin.object"))
        x
    else np_array(x)))
    callable <- if (missing(y_true) && missing(y_pred))
        keras$losses$MeanAbsoluteError
    else keras$losses$mean_absolute_error
    do.call(callable, args)
}, py_function_name = "mean_absolute_error")


"man-src/loss_mean_absolute_percentage_error.Rmd" # |>file.edit() # or cmd+click to edit man page
"man-src/loss_mean_absolute_percentage_error/0-upstream.md" # view the upstream doc
#' @eval readLines("man-src/loss_mean_absolute_percentage_error/3-rendered.md")
loss_mean_absolute_percentage_error <-
structure(function (y_true, y_pred, ..., reduction = "sum_over_batch_size",
    name = "mean_absolute_percentage_error")
{
    args <- capture_args2(list(y_true = function (x)
    if (inherits(x, "python.builtin.object"))
        x
    else np_array(x), y_pred = function (x)
    if (inherits(x, "python.builtin.object"))
        x
    else np_array(x)))
    callable <- if (missing(y_true) && missing(y_pred))
        keras$losses$MeanAbsolutePercentageError
    else keras$losses$mean_absolute_percentage_error
    do.call(callable, args)
}, py_function_name = "mean_absolute_percentage_error")


"man-src/loss_mean_squared_error.Rmd" # |>file.edit() # or cmd+click to edit man page
"man-src/loss_mean_squared_error/0-upstream.md" # view the upstream doc
#' @eval readLines("man-src/loss_mean_squared_error/3-rendered.md")
loss_mean_squared_error <-
structure(function (y_true, y_pred, ..., reduction = "sum_over_batch_size",
    name = "mean_squared_error")
{
    args <- capture_args2(list(y_true = function (x)
    if (inherits(x, "python.builtin.object"))
        x
    else np_array(x), y_pred = function (x)
    if (inherits(x, "python.builtin.object"))
        x
    else np_array(x)))
    callable <- if (missing(y_true) && missing(y_pred))
        keras$losses$MeanSquaredError
    else keras$losses$mean_squared_error
    do.call(callable, args)
}, py_function_name = "mean_squared_error")


"man-src/loss_mean_squared_logarithmic_error.Rmd" # |>file.edit() # or cmd+click to edit man page
"man-src/loss_mean_squared_logarithmic_error/0-upstream.md" # view the upstream doc
#' @eval readLines("man-src/loss_mean_squared_logarithmic_error/3-rendered.md")
loss_mean_squared_logarithmic_error <-
structure(function (y_true, y_pred, ..., reduction = "sum_over_batch_size",
    name = "mean_squared_logarithmic_error")
{
    args <- capture_args2(list(y_true = function (x)
    if (inherits(x, "python.builtin.object"))
        x
    else np_array(x), y_pred = function (x)
    if (inherits(x, "python.builtin.object"))
        x
    else np_array(x)))
    callable <- if (missing(y_true) && missing(y_pred))
        keras$losses$MeanSquaredLogarithmicError
    else keras$losses$mean_squared_logarithmic_error
    do.call(callable, args)
}, py_function_name = "mean_squared_logarithmic_error")


"man-src/loss_poisson.Rmd" # |>file.edit() # or cmd+click to edit man page
"man-src/loss_poisson/0-upstream.md" # view the upstream doc
#' @eval readLines("man-src/loss_poisson/3-rendered.md")
loss_poisson <-
structure(function (y_true, y_pred, ..., reduction = "sum_over_batch_size",
    name = "poisson")
{
    args <- capture_args2(list(y_true = function (x)
    if (inherits(x, "python.builtin.object"))
        x
    else np_array(x), y_pred = function (x)
    if (inherits(x, "python.builtin.object"))
        x
    else np_array(x)))
    callable <- if (missing(y_true) && missing(y_pred))
        keras$losses$Poisson
    else keras$losses$poisson
    do.call(callable, args)
}, py_function_name = "poisson")


"man-src/loss_sparse_categorical_crossentropy.Rmd" # |>file.edit() # or cmd+click to edit man page
"man-src/loss_sparse_categorical_crossentropy/0-upstream.md" # view the upstream doc
#' @eval readLines("man-src/loss_sparse_categorical_crossentropy/3-rendered.md")
loss_sparse_categorical_crossentropy <-
structure(function (y_true, y_pred, from_logits = FALSE, ignore_class = NULL,
    axis = -1L, ..., reduction = "sum_over_batch_size", name = "sparse_categorical_crossentropy")
{
    args <- capture_args2(list(ignore_class = as_integer, y_true = function (x)
    if (inherits(x, "python.builtin.object"))
        x
    else np_array(x), y_pred = function (x)
    if (inherits(x, "python.builtin.object"))
        x
    else np_array(x), axis = as_axis))
    callable <- if (missing(y_true) && missing(y_pred))
        keras$losses$SparseCategoricalCrossentropy
    else keras$losses$sparse_categorical_crossentropy
    do.call(callable, args)
}, py_function_name = "sparse_categorical_crossentropy")


"man-src/loss_squared_hinge.Rmd" # |>file.edit() # or cmd+click to edit man page
"man-src/loss_squared_hinge/0-upstream.md" # view the upstream doc
#' @eval readLines("man-src/loss_squared_hinge/3-rendered.md")
loss_squared_hinge <-
structure(function (y_true, y_pred, ..., reduction = "sum_over_batch_size",
    name = "squared_hinge")
{
    args <- capture_args2(list(y_true = function (x)
    if (inherits(x, "python.builtin.object"))
        x
    else np_array(x), y_pred = function (x)
    if (inherits(x, "python.builtin.object"))
        x
    else np_array(x)))
    callable <- if (missing(y_true) && missing(y_pred))
        keras$losses$SquaredHinge
    else keras$losses$squared_hinge
    do.call(callable, args)
}, py_function_name = "squared_hinge")
