## Autogenerated. Do not modify manually.


#' @eval readLines("man-roxygen/k_image_affine_transform/roxygen.Rmd")
k_image_affine_transform <-
function (image, transform, interpolation = "bilinear", fill_mode = "constant",
    fill_value = 0L, data_format = "channels_last")
{
    args <- capture_args2(list(fill_value = as_integer))
    do.call(keras$ops$image$affine_transform, args)
}


#' @eval readLines("man-roxygen/k_image_extract_patches/roxygen.Rmd")
k_image_extract_patches <-
function (image, size, strides = NULL, dilation_rate = 1L, padding = "valid",
    data_format = "channels_last")
{
    args <- capture_args2(list(size = as_integer, dilation_rate = as_integer))
    do.call(keras$ops$image$extract_patches, args)
}


#' @eval readLines("man-roxygen/k_image_map_coordinates/roxygen.Rmd")
k_image_map_coordinates <-
function (input, coordinates, order, fill_mode = "constant",
    fill_value = 0L)
{
    args <- capture_args2(list(fill_value = as_integer))
    do.call(keras$ops$image$map_coordinates, args)
}


#' @eval readLines("man-roxygen/k_image_pad_images/roxygen.Rmd")
k_image_pad_images <-
function (images, top_padding = NULL, left_padding = NULL, target_height = NULL,
    target_width = NULL, bottom_padding = NULL, right_padding = NULL)
keras$ops$image$pad_images(images, top_padding, left_padding,
    target_height, target_width, bottom_padding, right_padding)


#' @eval readLines("man-roxygen/k_image_resize/roxygen.Rmd")
k_image_resize <-
function (image, size, interpolation = "bilinear", antialias = FALSE,
    data_format = "channels_last")
keras$ops$image$resize(image, size, interpolation, antialias,
    data_format)
