## Autogenerated. Do not modify manually.


"man-src/learning_rate_schedule_cosine_decay/2-translated.Rmd" # |>file.edit() # or cmd+click to edit man page
#' @eval readLines("man-src/learning_rate_schedule_cosine_decay/3-rendered.md")
learning_rate_schedule_cosine_decay <-
function (initial_learning_rate, decay_steps, alpha = 0, name = "CosineDecay",
    warmup_target = NULL, warmup_steps = 0L)
{
    args <- capture_args2(list(decay_steps = as_integer, warmup_steps = as_integer))
    do.call(keras$optimizers$schedules$CosineDecay, args)
}


"man-src/learning_rate_schedule_cosine_decay_restarts/2-translated.Rmd" # |>file.edit() # or cmd+click to edit man page
#' @eval readLines("man-src/learning_rate_schedule_cosine_decay_restarts/3-rendered.md")
learning_rate_schedule_cosine_decay_restarts <-
function (initial_learning_rate, first_decay_steps, t_mul = 2,
    m_mul = 1, alpha = 0, name = "SGDRDecay")
{
    args <- capture_args2(list(first_decay_steps = as_integer))
    do.call(keras$optimizers$schedules$CosineDecayRestarts, args)
}


"man-src/learning_rate_schedule_exponential_decay/2-translated.Rmd" # |>file.edit() # or cmd+click to edit man page
#' @eval readLines("man-src/learning_rate_schedule_exponential_decay/3-rendered.md")
learning_rate_schedule_exponential_decay <-
function (initial_learning_rate, decay_steps, decay_rate, staircase = FALSE,
    name = "ExponentialDecay")
{
    args <- capture_args2(list(decay_steps = as_integer))
    do.call(keras$optimizers$schedules$ExponentialDecay, args)
}


"man-src/learning_rate_schedule_inverse_time_decay/2-translated.Rmd" # |>file.edit() # or cmd+click to edit man page
#' @eval readLines("man-src/learning_rate_schedule_inverse_time_decay/3-rendered.md")
learning_rate_schedule_inverse_time_decay <-
function (initial_learning_rate, decay_steps, decay_rate, staircase = FALSE,
    name = "InverseTimeDecay")
{
    args <- capture_args2(NULL)
    do.call(keras$optimizers$schedules$InverseTimeDecay, args)
}


"man-src/learning_rate_schedule_piecewise_constant_decay/2-translated.Rmd" # |>file.edit() # or cmd+click to edit man page
#' @eval readLines("man-src/learning_rate_schedule_piecewise_constant_decay/3-rendered.md")
learning_rate_schedule_piecewise_constant_decay <-
function (boundaries, values, name = "PiecewiseConstant")
{
    args <- capture_args2(NULL)
    do.call(keras$optimizers$schedules$PiecewiseConstantDecay,
        args)
}


"man-src/learning_rate_schedule_polynomial_decay/2-translated.Rmd" # |>file.edit() # or cmd+click to edit man page
#' @eval readLines("man-src/learning_rate_schedule_polynomial_decay/3-rendered.md")
learning_rate_schedule_polynomial_decay <-
function (initial_learning_rate, decay_steps, end_learning_rate = 1e-04,
    power = 1, cycle = FALSE, name = "PolynomialDecay")
{
    args <- capture_args2(list(decay_steps = as_integer))
    do.call(keras$optimizers$schedules$PolynomialDecay, args)
}
