## Autogenerated. Do not modify manually.


"man-src/constraint_maxnorm.Rmd" # |>file.edit() # or cmd+click to edit man page
"man-src/constraint_maxnorm/0-upstream.md" # view the upstream doc
#' @eval readLines("man-src/constraint_maxnorm/3-rendered.md")
constraint_maxnorm <-
function (max_value = 2L, axis = 0L)
{
    args <- capture_args2(list(max_value = as_integer, axis = as_axis))
    do.call(keras$constraints$MaxNorm, args)
}


"man-src/constraint_minmaxnorm.Rmd" # |>file.edit() # or cmd+click to edit man page
"man-src/constraint_minmaxnorm/0-upstream.md" # view the upstream doc
#' @eval readLines("man-src/constraint_minmaxnorm/3-rendered.md")
constraint_minmaxnorm <-
function (min_value = 0, max_value = 1, rate = 1, axis = 0L)
{
    args <- capture_args2(list(axis = as_axis))
    do.call(keras$constraints$MinMaxNorm, args)
}


"man-src/constraint_nonneg.Rmd" # |>file.edit() # or cmd+click to edit man page
"man-src/constraint_nonneg/0-upstream.md" # view the upstream doc
#' @eval readLines("man-src/constraint_nonneg/3-rendered.md")
constraint_nonneg <-
function ()
{
    args <- capture_args2(NULL)
    do.call(keras$constraints$NonNeg, args)
}


"man-src/constraint_unitnorm.Rmd" # |>file.edit() # or cmd+click to edit man page
"man-src/constraint_unitnorm/0-upstream.md" # view the upstream doc
#' @eval readLines("man-src/constraint_unitnorm/3-rendered.md")
constraint_unitnorm <-
function (axis = 0L)
{
    args <- capture_args2(list(axis = as_axis))
    do.call(keras$constraints$UnitNorm, args)
}
