## Autogenerated. Do not modify manually.


"man-src/clear_session.Rmd" # |>file.edit() # or cmd+click to edit man page
"man-src/clear_session/0-upstream.md" # view the upstream doc
#' @eval readLines("man-src/clear_session/3-rendered.md")
clear_session <-
function ()
{
    args <- capture_args2(NULL)
    do.call(keras$utils$clear_session, args)
}


"man-src/layer_feature_space.Rmd" # |>file.edit() # or cmd+click to edit man page
"man-src/layer_feature_space/0-upstream.md" # view the upstream doc
#' @eval readLines("man-src/layer_feature_space/3-rendered.md")
layer_feature_space <-
function (object, features, output_mode = "concat", crosses = NULL,
    crossing_dim = 32L, hashing_dim = 32L, num_discretization_bins = 32L,
    name = NULL, feature_names = NULL)
{
    args <- capture_args2(list(crossing_dim = as_integer, hashing_dim = as_integer,
        num_discretization_bins = as_integer, feature_names = as_integer),
        ignore = "object")
    create_layer(keras$utils$FeatureSpace, object, args)
}


"man-src/get_source_inputs.Rmd" # |>file.edit() # or cmd+click to edit man page
"man-src/get_source_inputs/0-upstream.md" # view the upstream doc
#' @eval readLines("man-src/get_source_inputs/3-rendered.md")
get_source_inputs <-
function (tensor)
{
    args <- capture_args2(NULL)
    do.call(keras$utils$get_source_inputs, args)
}


"man-src/get_custom_objects.Rmd" # |>file.edit() # or cmd+click to edit man page
"man-src/get_custom_objects/0-upstream.md" # view the upstream doc
#' @eval readLines("man-src/get_custom_objects/3-rendered.md")
get_custom_objects <-
function ()
{
    args <- capture_args2(NULL)
    do.call(keras$utils$get_custom_objects, args)
}


"man-src/get_registered_name.Rmd" # |>file.edit() # or cmd+click to edit man page
"man-src/get_registered_name/0-upstream.md" # view the upstream doc
#' @eval readLines("man-src/get_registered_name/3-rendered.md")
get_registered_name <-
function (obj)
{
    args <- capture_args2(NULL)
    do.call(keras$utils$get_registered_name, args)
}


"man-src/get_registered_object.Rmd" # |>file.edit() # or cmd+click to edit man page
"man-src/get_registered_object/0-upstream.md" # view the upstream doc
#' @eval readLines("man-src/get_registered_object/3-rendered.md")
get_registered_object <-
function (name, custom_objects = NULL, module_objects = NULL)
{
    args <- capture_args2(NULL)
    do.call(keras$utils$get_registered_object, args)
}


"man-src/pack_x_y_sample_weight.Rmd" # |>file.edit() # or cmd+click to edit man page
"man-src/pack_x_y_sample_weight/0-upstream.md" # view the upstream doc
#' @eval readLines("man-src/pack_x_y_sample_weight/3-rendered.md")
pack_x_y_sample_weight <-
function (x, y = NULL, sample_weight = NULL)
{
    args <- capture_args2(NULL)
    do.call(keras$utils$pack_x_y_sample_weight, args)
}


"man-src/unpack_x_y_sample_weight.Rmd" # |>file.edit() # or cmd+click to edit man page
"man-src/unpack_x_y_sample_weight/0-upstream.md" # view the upstream doc
#' @eval readLines("man-src/unpack_x_y_sample_weight/3-rendered.md")
unpack_x_y_sample_weight <-
function (data)
{
    args <- capture_args2(NULL)
    do.call(keras$utils$unpack_x_y_sample_weight, args)
}


"man-src/audio_dataset_from_directory.Rmd" # |>file.edit() # or cmd+click to edit man page
"man-src/audio_dataset_from_directory/0-upstream.md" # view the upstream doc
#' @eval readLines("man-src/audio_dataset_from_directory/3-rendered.md")
audio_dataset_from_directory <-
function (directory, labels = "inferred", label_mode = "int",
    class_names = NULL, batch_size = 32L, sampling_rate = NULL,
    output_sequence_length = NULL, ragged = FALSE, shuffle = TRUE,
    seed = NULL, validation_split = NULL, subset = NULL, follow_links = FALSE)
{
    args <- capture_args2(list(labels = as_integer, label_mode = as_integer,
        batch_size = as_integer, seed = as_integer))
    do.call(keras$utils$audio_dataset_from_directory, args)
}


"man-src/split_dataset.Rmd" # |>file.edit() # or cmd+click to edit man page
"man-src/split_dataset/0-upstream.md" # view the upstream doc
#' @eval readLines("man-src/split_dataset/3-rendered.md")
split_dataset <-
function (dataset, left_size = NULL, right_size = NULL, shuffle = FALSE,
    seed = NULL)
{
    args <- capture_args2(list(left_size = as_integer, right_size = as_integer,
        seed = as_integer))
    do.call(keras$utils$split_dataset, args)
}


"man-src/get_file.Rmd" # |>file.edit() # or cmd+click to edit man page
"man-src/get_file/0-upstream.md" # view the upstream doc
#' @eval readLines("man-src/get_file/3-rendered.md")
get_file <-
function (fname = NULL, origin = NULL, untar = FALSE, md5_hash = NULL,
    file_hash = NULL, cache_subdir = "datasets", hash_algorithm = "auto",
    extract = FALSE, archive_format = "auto", cache_dir = NULL)
{
    args <- capture_args2(NULL)
    do.call(keras$utils$get_file, args)
}


"man-src/image_dataset_from_directory.Rmd" # |>file.edit() # or cmd+click to edit man page
"man-src/image_dataset_from_directory/0-upstream.md" # view the upstream doc
#' @eval readLines("man-src/image_dataset_from_directory/3-rendered.md")
image_dataset_from_directory <-
function (directory, labels = "inferred", label_mode = "int",
    class_names = NULL, color_mode = "rgb", batch_size = 32L,
    image_size = list(256L, 256L), shuffle = TRUE, seed = NULL,
    validation_split = NULL, subset = NULL, interpolation = "bilinear",
    follow_links = FALSE, crop_to_aspect_ratio = FALSE, data_format = NULL)
{
    args <- capture_args2(list(labels = as_integer, label_mode = as_integer,
        batch_size = as_integer, seed = as_integer))
    do.call(keras$utils$image_dataset_from_directory, args)
}


"man-src/image_array_save.Rmd" # |>file.edit() # or cmd+click to edit man page
"man-src/image_array_save/0-upstream.md" # view the upstream doc
#' @eval readLines("man-src/image_array_save/3-rendered.md")
image_array_save <-
function (x, path, data_format = NULL, file_format = NULL, scale = TRUE,
    ...)
{
    args <- capture_args2(NULL)
    do.call(keras$utils$save_img, args)
}


"man-src/image_from_array.Rmd" # |>file.edit() # or cmd+click to edit man page
"man-src/image_from_array/0-upstream.md" # view the upstream doc
#' @eval readLines("man-src/image_from_array/3-rendered.md")
image_from_array <-
function (x, data_format = NULL, scale = TRUE, dtype = NULL)
{
    args <- capture_args2(NULL)
    do.call(keras$utils$array_to_img, args)
}


"man-src/image_load.Rmd" # |>file.edit() # or cmd+click to edit man page
"man-src/image_load/0-upstream.md" # view the upstream doc
#' @eval readLines("man-src/image_load/3-rendered.md")
image_load <-
function (path, color_mode = "rgb", target_size = NULL, interpolation = "nearest",
    keep_aspect_ratio = FALSE)
{
    args <- capture_args2(NULL)
    do.call(keras$utils$load_img, args)
}


"man-src/image_to_array.Rmd" # |>file.edit() # or cmd+click to edit man page
"man-src/image_to_array/0-upstream.md" # view the upstream doc
#' @eval readLines("man-src/image_to_array/3-rendered.md")
image_to_array <-
function (img, data_format = NULL, dtype = NULL)
{
    args <- capture_args2(NULL)
    do.call(keras$utils$img_to_array, args)
}


"man-src/model_to_dot.Rmd" # |>file.edit() # or cmd+click to edit man page
"man-src/model_to_dot/0-upstream.md" # view the upstream doc
#' @eval readLines("man-src/model_to_dot/3-rendered.md")
model_to_dot <-
function (model, show_shapes = FALSE, show_dtype = FALSE, show_layer_names = TRUE,
    rankdir = "TB", expand_nested = FALSE, dpi = 200L, subgraph = FALSE,
    show_layer_activations = FALSE, show_trainable = FALSE, ...)
{
    args <- capture_args2(list(dpi = as_integer))
    do.call(keras$utils$model_to_dot, args)
}


"man-src/normalize.Rmd" # |>file.edit() # or cmd+click to edit man page
"man-src/normalize/0-upstream.md" # view the upstream doc
#' @eval readLines("man-src/normalize/3-rendered.md")
normalize <-
function (x, axis = -1L, order = 2L)
{
    args <- capture_args2(list(axis = as_axis, order = as_integer))
    do.call(keras$utils$normalize, args)
}


"man-src/to_categorical.Rmd" # |>file.edit() # or cmd+click to edit man page
"man-src/to_categorical/0-upstream.md" # view the upstream doc
#' @eval readLines("man-src/to_categorical/3-rendered.md")
to_categorical <-
function (x, num_classes = NULL)
{
    args <- capture_args2(list(x = as_integer_array, num_classes = as_integer))
    do.call(keras$utils$to_categorical, args)
}


"man-src/set_random_seed.Rmd" # |>file.edit() # or cmd+click to edit man page
"man-src/set_random_seed/0-upstream.md" # view the upstream doc
#' @eval readLines("man-src/set_random_seed/3-rendered.md")
set_random_seed <-
function (seed)
{
    args <- capture_args2(list(seed = as_integer))
    set.seed(args$seed)
    do.call(keras$utils$set_random_seed, args)
}


"man-src/pad_sequences.Rmd" # |>file.edit() # or cmd+click to edit man page
"man-src/pad_sequences/0-upstream.md" # view the upstream doc
#' @eval readLines("man-src/pad_sequences/3-rendered.md")
pad_sequences <-
function (sequences, maxlen = NULL, dtype = "int32", padding = "pre",
    truncating = "pre", value = 0)
{
    args <- capture_args2(list(maxlen = as_integer))
    do.call(keras$utils$pad_sequences, args)
}


"man-src/text_dataset_from_directory.Rmd" # |>file.edit() # or cmd+click to edit man page
"man-src/text_dataset_from_directory/0-upstream.md" # view the upstream doc
#' @eval readLines("man-src/text_dataset_from_directory/3-rendered.md")
text_dataset_from_directory <-
function (directory, labels = "inferred", label_mode = "int",
    class_names = NULL, batch_size = 32L, max_length = NULL,
    shuffle = TRUE, seed = NULL, validation_split = NULL, subset = NULL,
    follow_links = FALSE)
{
    args <- capture_args2(list(labels = as_integer, label_mode = as_integer,
        batch_size = as_integer, seed = as_integer))
    do.call(keras$utils$text_dataset_from_directory, args)
}


"man-src/timeseries_dataset_from_array.Rmd" # |>file.edit() # or cmd+click to edit man page
"man-src/timeseries_dataset_from_array/0-upstream.md" # view the upstream doc
#' @eval readLines("man-src/timeseries_dataset_from_array/3-rendered.md")
timeseries_dataset_from_array <-
function (data, targets, sequence_length, sequence_stride = 1L,
    sampling_rate = 1L, batch_size = 128L, shuffle = FALSE, seed = NULL,
    start_index = NULL, end_index = NULL)
{
    args <- capture_args2(list(sequence_stride = as_integer,
        sampling_rate = as_integer, batch_size = as_integer,
        seed = as_integer, start_index = as_integer, end_index = as_integer))
    do.call(keras$utils$timeseries_dataset_from_array, args)
}
