Compute the weighted average along the specified axis.

@description

# Examples
```{r}
data <- k_arange(1, 5, dtype = "int32")
data
k_average(data)

k_average(
  k_arange(1, 11),
  weights = k_arange(10, 0, -1)
)

data <- k_arange(6) |> k_reshape(c(3, 2))
data

k_average(
  data,
  axis = 2,
  weights = k_array(c(1/4, 3/4))
)

try(k_average(
  data,
  weights = k_array(c(1/4, 3/4))
))
# Error: Axis must be specified when shapes of a and weights differ.
```

@returns
Return the average along the specified axis.

@param x Input tensor.
@param axis Integer along which to average `x`. The default, `axis=NULL`,
    will average over all of the elements of the input tensor. If axis
    is negative it counts from the last to the first axis.
@param weights Tensor of wieghts associated with the values in `x`. Each
    value in `x` contributes to the average according to its
    associated weight. The weights array can either be 1-D (in which
    case its length must be the size of a along the given axis) or of
    the same shape as `x`. If `weights=NULL` (default), then all data
    in `x` are assumed to have a weight equal to one.

    The 1-D calculation is: `avg = sum(a * weights) / sum(weights)`.
    The only constraint on weights is that `sum(weights)` must not be 0.

@export
@family ops
@seealso
+ <https://www.tensorflow.org/api_docs/python/tf/keras/ops/average>
